// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dashboard
extern void ui_dashboard_screen_init(void);
extern void ui_dashboard_screen_destroy(void);
extern void ui_event_dashboard(lv_event_t * e);
extern lv_obj_t * ui_dashboard;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_humd;
extern lv_obj_t * ui_humdlabel;
extern lv_obj_t * ui_degreecelcius;
extern void ui_event_Container7(lv_event_t * e);
extern lv_obj_t * ui_Container7;
extern void ui_event_PM1Button(lv_event_t * e);
extern lv_obj_t * ui_PM1Button;
extern lv_obj_t * ui_pm1value;
extern lv_obj_t * ui_pm1label;
extern lv_obj_t * ui_pm1unit;
extern lv_obj_t * ui_pm1cube;
extern lv_obj_t * ui_Container9;
extern void ui_event_PM25Button(lv_event_t * e);
extern lv_obj_t * ui_PM25Button;
extern lv_obj_t * ui_pm25label;
extern lv_obj_t * ui_pm25value;
extern lv_obj_t * ui_pmunit1;
extern lv_obj_t * ui_pm25cube;
extern void ui_event_Container8(lv_event_t * e);
extern lv_obj_t * ui_Container8;
extern void ui_event_PM4Button(lv_event_t * e);
extern lv_obj_t * ui_PM4Button;
extern lv_obj_t * ui_pm4value;
extern lv_obj_t * ui_pm4label;
extern lv_obj_t * ui_pm4unit;
extern lv_obj_t * ui_pm4cube;
extern lv_obj_t * ui_Container10;
extern void ui_event_PM10Button(lv_event_t * e);
extern lv_obj_t * ui_PM10Button;
extern lv_obj_t * ui_pm10value;
extern lv_obj_t * ui_pm10label;
extern lv_obj_t * ui_pm10unit;
extern lv_obj_t * ui_pm10cube;
extern void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
extern void ui_event_TVOCButton(lv_event_t * e);
extern lv_obj_t * ui_TVOCButton;
extern lv_obj_t * ui_tvoclabel;
extern lv_obj_t * ui_tvocunit;
extern lv_obj_t * ui_tvocvalue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

