// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_dashboard = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_humd = NULL;
lv_obj_t * ui_humdlabel = NULL;
lv_obj_t * ui_degreecelcius = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_PM1Button = NULL;
lv_obj_t * ui_pm1value = NULL;
lv_obj_t * ui_pm1label = NULL;
lv_obj_t * ui_pm1unit = NULL;
lv_obj_t * ui_pm1cube = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_PM25Button = NULL;
lv_obj_t * ui_pm25label = NULL;
lv_obj_t * ui_pm25value = NULL;
lv_obj_t * ui_pmunit1 = NULL;
lv_obj_t * ui_pm25cube = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_PM4Button = NULL;
lv_obj_t * ui_pm4value = NULL;
lv_obj_t * ui_pm4label = NULL;
lv_obj_t * ui_pm4unit = NULL;
lv_obj_t * ui_pm4cube = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_PM10Button = NULL;
lv_obj_t * ui_pm10value = NULL;
lv_obj_t * ui_pm10label = NULL;
lv_obj_t * ui_pm10unit = NULL;
lv_obj_t * ui_pm10cube = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_TVOCButton = NULL;
lv_obj_t * ui_tvoclabel = NULL;
lv_obj_t * ui_tvocunit = NULL;
lv_obj_t * ui_tvocvalue = NULL;
// event funtions
void ui_event_dashboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_owl, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 15000, &ui_owl_screen_init);
    }
}

void ui_event_Container7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM1graph, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PM1graph_screen_init);
    }
}

void ui_event_PM1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM1graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM1graph_screen_init);
    }
}

void ui_event_PM25Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM25graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM25graph_screen_init);
    }
}

void ui_event_Container8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM1graph, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PM1graph_screen_init);
    }
}

void ui_event_PM4Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM4graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM4graph_screen_init);
    }
}

void ui_event_PM10Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM10graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM10graph_screen_init);
    }
}

void ui_event_Container11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TVOCgraph, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TVOCgraph_screen_init);
    }
}

void ui_event_TVOCButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TVOCgraph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_TVOCgraph_screen_init);
    }
}

// build funtions

void ui_dashboard_screen_init(void)
{
    ui_dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dashboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dashboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 238);
    lv_obj_set_height(ui_Container6, 59);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, -129);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, 0);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:25:45");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -95);
    lv_obj_set_y(ui_temp, 0);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "26.5");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humd = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_humd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humd, 61);
    lv_obj_set_y(ui_humd, 0);
    lv_obj_set_align(ui_humd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humd, "58");
    lv_obj_set_style_text_color(ui_humd, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humd, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humdlabel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_humdlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humdlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humdlabel, 98);
    lv_obj_set_y(ui_humdlabel, 0);
    lv_obj_set_align(ui_humdlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humdlabel, "RH%");
    lv_obj_set_style_text_color(ui_humdlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humdlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humdlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_degreecelcius = lv_img_create(ui_Container6);
    lv_img_set_src(ui_degreecelcius, &ui_img_582762761);
    lv_obj_set_width(ui_degreecelcius, 31);
    lv_obj_set_height(ui_degreecelcius, 33);
    lv_obj_set_x(ui_degreecelcius, -70);
    lv_obj_set_y(ui_degreecelcius, 0);
    lv_obj_set_align(ui_degreecelcius, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_degreecelcius, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_degreecelcius, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_degreecelcius, 140);

    ui_Container7 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 119);
    lv_obj_set_height(ui_Container7, 100);
    lv_obj_set_x(ui_Container7, -60);
    lv_obj_set_y(ui_Container7, -50);   
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM1Button = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_PM1Button, 112);
    lv_obj_set_height(ui_PM1Button, 95);
    lv_obj_set_x(ui_PM1Button, 1);
    lv_obj_set_y(ui_PM1Button, 0);
    lv_obj_set_align(ui_PM1Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PM1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PM1Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM1Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM1Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1value = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_pm1value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1value, -0);
    lv_obj_set_y(ui_pm1value, 15);
    lv_obj_set_align(ui_pm1value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1value, "1200");
    lv_obj_set_style_text_color(ui_pm1value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1value, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1label = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_pm1label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1label, -27);
    lv_obj_set_y(ui_pm1label, -25);
    lv_obj_set_align(ui_pm1label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1label, "PM1.0");
    lv_obj_set_style_text_color(ui_pm1label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1unit = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_pm1unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1unit, 30);
    lv_obj_set_y(ui_pm1unit, -25);
    lv_obj_set_align(ui_pm1unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm1unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1unit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1cube = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_pm1cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1cube, 50);
    lv_obj_set_y(ui_pm1cube, -35);
    lv_obj_set_align(ui_pm1cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1cube, "3");
    lv_obj_set_style_text_color(ui_pm1cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1cube, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 119);
    lv_obj_set_height(ui_Container9, 100);
    lv_obj_set_x(ui_Container9, -60);
    lv_obj_set_y(ui_Container9, 50);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25Button = lv_btn_create(ui_Container9);
    lv_obj_set_width(ui_PM25Button, 111);
    lv_obj_set_height(ui_PM25Button, 92);
    lv_obj_set_align(ui_PM25Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM25Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PM25Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PM25Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM25Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25label = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_pm25label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25label, -25);
    lv_obj_set_y(ui_pm25label, -25);
    lv_obj_set_align(ui_pm25label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25label, "PM2.5");
    lv_obj_set_style_text_color(ui_pm25label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25value = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_pm25value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25value, 0);
    lv_obj_set_y(ui_pm25value, 15);
    lv_obj_set_align(ui_pm25value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25value, "1600");
    lv_obj_set_style_text_color(ui_pm25value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25value, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmunit1 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_pmunit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmunit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmunit1, 30);
    lv_obj_set_y(ui_pmunit1, -25);
    lv_obj_set_align(ui_pmunit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pmunit1, "ug/m");
    lv_obj_set_style_text_color(ui_pmunit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pmunit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pmunit1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25cube = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_pm25cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25cube, 53);
    lv_obj_set_y(ui_pm25cube, -35);
    lv_obj_set_align(ui_pm25cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25cube, "3");
    lv_obj_set_style_text_color(ui_pm25cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25cube, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 119);
    lv_obj_set_height(ui_Container8, 100);
    lv_obj_set_x(ui_Container8, 59);
    lv_obj_set_y(ui_Container8, -50);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM4Button = lv_btn_create(ui_Container8);
    lv_obj_set_width(ui_PM4Button, 112);
    lv_obj_set_height(ui_PM4Button, 92);
    lv_obj_set_align(ui_PM4Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM4Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PM4Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PM4Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM4Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM4Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4value = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_pm4value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4value, 0);
    lv_obj_set_y(ui_pm4value, 15);
    lv_obj_set_align(ui_pm4value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4value, "1400");
    lv_obj_set_style_text_color(ui_pm4value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4value, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4label = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_pm4label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4label, -25);
    lv_obj_set_y(ui_pm4label, -25);
    lv_obj_set_align(ui_pm4label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4label, "PM4.0");
    lv_obj_set_style_text_color(ui_pm4label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4unit = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_pm4unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4unit, 30);
    lv_obj_set_y(ui_pm4unit, -25);
    lv_obj_set_align(ui_pm4unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm4unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4unit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4cube = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_pm4cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4cube, 51);
    lv_obj_set_y(ui_pm4cube, -35);
    lv_obj_set_align(ui_pm4cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4cube, "3");
    lv_obj_set_style_text_color(ui_pm4cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4cube, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 119);
    lv_obj_set_height(ui_Container10, 100);
    lv_obj_set_x(ui_Container10, 59);
    lv_obj_set_y(ui_Container10, 49);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM10Button = lv_btn_create(ui_Container10);
    lv_obj_set_width(ui_PM10Button, 113);
    lv_obj_set_height(ui_PM10Button, 96);
    lv_obj_set_align(ui_PM10Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM10Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PM10Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PM10Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PM10Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM10Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10value = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_pm10value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10value, 0);
    lv_obj_set_y(ui_pm10value, 15);
    lv_obj_set_align(ui_pm10value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10value, "1136");
    lv_obj_set_style_text_color(ui_pm10value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10value, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10label = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_pm10label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10label, -23);
    lv_obj_set_y(ui_pm10label, -25);
    lv_obj_set_align(ui_pm10label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10label, "PM10.0");
    lv_obj_set_style_text_color(ui_pm10label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10unit = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_pm10unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10unit, 35);
    lv_obj_set_y(ui_pm10unit, -25);
    lv_obj_set_align(ui_pm10unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm10unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10unit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10cube = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_pm10cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10cube, 54);
    lv_obj_set_y(ui_pm10cube, -35);
    lv_obj_set_align(ui_pm10cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10cube, "3");
    lv_obj_set_style_text_color(ui_pm10cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10cube, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 238);
    lv_obj_set_height(ui_Container11, 59);
    lv_obj_set_x(ui_Container11, 0);
    lv_obj_set_y(ui_Container11, 128);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCButton = lv_btn_create(ui_Container11);
    lv_obj_set_width(ui_TVOCButton, 233);
    lv_obj_set_height(ui_TVOCButton, 51);
    lv_obj_set_align(ui_TVOCButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TVOCButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TVOCButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TVOCButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TVOCButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvoclabel = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_tvoclabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvoclabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvoclabel, -77);
    lv_obj_set_y(ui_tvoclabel, 0);
    lv_obj_set_align(ui_tvoclabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvoclabel, "TVOC");
    lv_obj_set_style_text_color(ui_tvoclabel, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvoclabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvoclabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocunit = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_tvocunit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvocunit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvocunit, -19);
    lv_obj_set_y(ui_tvocunit, 0);
    lv_obj_set_align(ui_tvocunit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvocunit, "index");
    lv_obj_set_style_text_color(ui_tvocunit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvocunit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvocunit, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocvalue = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_tvocvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvocvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvocvalue, 50);
    lv_obj_set_y(ui_tvocvalue, 0);
    lv_obj_set_align(ui_tvocvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvocvalue, "1465");
    lv_obj_set_style_text_color(ui_tvocvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvocvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvocvalue, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PM1Button, ui_event_PM1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container7, ui_event_Container7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PM25Button, ui_event_PM25Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PM4Button, ui_event_PM4Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container8, ui_event_Container8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PM10Button, ui_event_PM10Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TVOCButton, ui_event_TVOCButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container11, ui_event_Container11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dashboard, ui_event_dashboard, LV_EVENT_ALL, NULL);

}

void ui_dashboard_screen_destroy(void)
{
    if(ui_dashboard) lv_obj_del(ui_dashboard);

    // NULL screen variables
    ui_dashboard = NULL;
    ui_Container6 = NULL;
    ui_time = NULL;
    ui_temp = NULL;
    ui_humd = NULL;
    ui_humdlabel = NULL;
    ui_degreecelcius = NULL;
    ui_Container7 = NULL;
    ui_PM1Button = NULL;
    ui_pm1value = NULL;
    ui_pm1label = NULL;
    ui_pm1unit = NULL;
    ui_pm1cube = NULL;
    ui_Container9 = NULL;
    ui_PM25Button = NULL;
    ui_pm25label = NULL;
    ui_pm25value = NULL;
    ui_pmunit1 = NULL;
    ui_pm25cube = NULL;
    ui_Container8 = NULL;
    ui_PM4Button = NULL;
    ui_pm4value = NULL;
    ui_pm4label = NULL;
    ui_pm4unit = NULL;
    ui_pm4cube = NULL;
    ui_Container10 = NULL;
    ui_PM10Button = NULL;
    ui_pm10value = NULL;
    ui_pm10label = NULL;
    ui_pm10unit = NULL;
    ui_pm10cube = NULL;
    ui_Container11 = NULL;
    ui_TVOCButton = NULL;
    ui_tvoclabel = NULL;
    ui_tvocunit = NULL;
    ui_tvocvalue = NULL;

}
