// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_eCO2graph;
lv_obj_t * ui_eCO2chart;
lv_obj_t * ui_graphparameter7;
lv_obj_t * ui_Container11;
lv_obj_t * ui_gpunit5;
lv_obj_t * ui_return5;
lv_obj_t * ui_returnlabel5;
lv_obj_t * ui_graphparameter16;
lv_obj_t * ui_graphparameter17;
lv_obj_t * ui_eco2avg1;
lv_obj_t * ui_eco2max1;
lv_obj_t * ui_eco2max2;

// event funtions
void ui_event_return5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_eCO2graph_screen_init(void)
{
    ui_eCO2graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_eCO2graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_eCO2graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_eCO2graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eCO2chart = lv_chart_create(ui_eCO2graph);
    lv_obj_set_width(ui_eCO2chart, 201);
    lv_obj_set_height(ui_eCO2chart, 195);
    lv_obj_set_x(ui_eCO2chart, 14);
    lv_obj_set_y(ui_eCO2chart, 4);
    lv_obj_set_align(ui_eCO2chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_eCO2chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_eCO2chart, 12);
    lv_chart_set_range(ui_eCO2chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_eCO2chart, 0, 0);
    lv_chart_set_zoom_x(ui_eCO2chart, 250);
    lv_chart_set_zoom_y(ui_eCO2chart, 250);
    lv_chart_set_axis_tick(ui_eCO2chart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_eCO2chart, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_eCO2chart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_eCO2chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_eCO2chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_eCO2chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_eCO2chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_eCO2chart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_eCO2chart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_eCO2chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_eCO2chart, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_eCO2graph);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 238);
    lv_obj_set_height(ui_Container11, 59);
    lv_obj_set_x(ui_Container11, 1);
    lv_obj_set_y(ui_Container11, -129);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter7 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_graphparameter7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter7, -74);
    lv_obj_set_y(ui_graphparameter7, 2);
    lv_obj_set_align(ui_graphparameter7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter7, "PM10.0");
    lv_obj_set_style_text_color(ui_graphparameter7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_graphparameter7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit5 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_gpunit5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit5, -4);
    lv_obj_set_y(ui_gpunit5, 2);
    lv_obj_set_align(ui_gpunit5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit5, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_cube3 = lv_label_create(ui_Container11);
    // lv_obj_set_width(ui_cube3, LV_SIZE_CONTENT);   /// 1
    // lv_obj_set_height(ui_cube3, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_cube3, 21);
    // lv_obj_set_y(ui_cube3, -11);
    // lv_obj_set_align(ui_cube3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_cube3, "3");
    // lv_obj_set_style_text_color(ui_cube3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_cube3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_cube3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eco2max1 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_eco2max1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_eco2max1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_eco2max1, 49);
    lv_obj_set_y(ui_eco2max1, 2);
    lv_obj_set_align(ui_eco2max1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_eco2max1, "max");
    lv_obj_set_style_text_color(ui_eco2max1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_eco2max1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_eco2max1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eco2max2 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_eco2max2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_eco2max2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_eco2max2, 85);
    lv_obj_set_y(ui_eco2max2, 1);
    lv_obj_set_align(ui_eco2max2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_eco2max2, "-");
    lv_obj_set_style_text_color(ui_eco2max2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_eco2max2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_eco2max2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return5 = lv_btn_create(ui_eCO2graph);
    lv_obj_set_width(ui_return5, 160);
    lv_obj_set_height(ui_return5, 39);
    lv_obj_set_x(ui_return5, 0);
    lv_obj_set_y(ui_return5, 127);
    lv_obj_set_align(ui_return5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return5, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel5 = lv_label_create(ui_return5);
    lv_obj_set_width(ui_returnlabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_returnlabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel5, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return5, ui_event_return3, LV_EVENT_ALL, NULL);

}


void ui_eCO2graph_screen_destroy(void)
{
    if(ui_eCO2graph) lv_obj_del(ui_eCO2graph);

    // NULL screen variables
    ui_eCO2graph = NULL;
    ui_eCO2chart = NULL;
    ui_graphparameter7 = NULL;
    ui_Container11 = NULL;
    ui_gpunit5 = NULL;
    ui_return5 = NULL;
    ui_returnlabel5 = NULL;
    ui_graphparameter16 = NULL;
    ui_graphparameter17 = NULL;
    ui_eco2avg1 = NULL;
    ui_eco2max1 = NULL;
    ui_eco2max2 = NULL;

}
