// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef UI_ECO2GRAPH_H
#define UI_ECO2GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_eCO2graph
extern void ui_eCO2graph_screen_init(void);
extern void ui_eCO2graph_screen_destroy(void);
extern lv_obj_t * ui_eCO2graph;
extern lv_obj_t * ui_eCO2chart;
extern lv_obj_t * ui_graphparameter7;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_gpunit5;
extern void ui_event_return5(lv_event_t * e);
extern lv_obj_t * ui_return5;
extern lv_obj_t * ui_returnlabel5;
extern lv_obj_t * ui_graphparameter16;
extern lv_obj_t * ui_graphparameter17;
extern lv_obj_t * ui_eco2avg1;
extern lv_obj_t * ui_eco2max1;
extern lv_obj_t * ui_eco2max2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

