// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef ui_HumdGRAPH_H
#define ui_HumdGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Humdgraph
extern void ui_Humdgraph_screen_init(void);
extern void ui_Humdgraph_screen_destroy(void);
extern lv_obj_t * ui_Humdgraph;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_humlabel;
extern lv_obj_t * ui_gpunit1;
extern lv_obj_t * ui_maxlabel1;
extern lv_obj_t * ui_Humdmaxvalue1;
extern void ui_event_return1(lv_event_t * e);
extern lv_obj_t * ui_return1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

