// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Intro = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_firmwareversion = NULL;
lv_obj_t * ui_devicename = NULL;
// event funtions
void ui_event_Intro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_qrcode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 8000, &ui_qrcode_screen_init);
    }
}

void ui_event_logo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        logoPressed(e);
        _ui_opacity_set(ui_logo, 100);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_opacity_set(ui_logo, 255);
    }
}

// build funtions

void ui_Intro_screen_init(void)
{
    ui_Intro = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Intro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Intro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Intro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_Intro);
    lv_img_set_src(ui_logo, &ui_img_oizom_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_firmwareversion = lv_label_create(ui_Intro);
    lv_obj_set_width(ui_firmwareversion, 85);
    lv_obj_set_height(ui_firmwareversion, 20);
    lv_obj_set_x(ui_firmwareversion, 0);
    lv_obj_set_y(ui_firmwareversion, -120);
    lv_obj_set_align(ui_firmwareversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareversion, "Version - 1.0");
    lv_obj_set_style_text_color(ui_firmwareversion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firmwareversion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_firmwareversion, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devicename = lv_label_create(ui_Intro);
    lv_obj_set_width(ui_devicename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devicename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_devicename, 0);
    lv_obj_set_y(ui_devicename, 120);
    lv_obj_set_align(ui_devicename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_devicename, "OIZOM AIROWL");
    lv_obj_set_style_text_color(ui_devicename, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_devicename, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_devicename, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_logo, ui_event_logo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Intro, ui_event_Intro, LV_EVENT_ALL, NULL);

}

void ui_Intro_screen_destroy(void)
{
    if(ui_Intro) lv_obj_del(ui_Intro);

    // NULL screen variables
    ui_Intro = NULL;
    ui_logo = NULL;
    ui_firmwareversion = NULL;
    ui_devicename = NULL;

}
