// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_INTRO_H
#define UI_INTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Intro
extern void ui_Intro_screen_init(void);
extern void ui_Intro_screen_destroy(void);
extern void ui_event_Intro(lv_event_t * e);
extern lv_obj_t * ui_Intro;
extern void ui_event_logo(lv_event_t * e);
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_firmwareversion;
extern lv_obj_t * ui_devicename;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

