// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: updated_airowl_ui

#ifndef UI_OWL_H
#define UI_OWL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_owl
extern void ui_owl_screen_init(void);
extern void ui_owl_screen_destroy(void);
extern void ui_event_owl(lv_event_t * e);
extern lv_obj_t * ui_owl;
extern lv_obj_t * ui_lefteye;
extern lv_obj_t * ui_leftpupil;
extern lv_obj_t * ui_righteye;
extern lv_obj_t * ui_rightpupil;
extern lv_obj_t * ui_nose;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

