// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: updated_airowl_ui

#include "../ui.h"

lv_obj_t * ui_owl = NULL;
lv_obj_t * ui_lefteye = NULL;
lv_obj_t * ui_leftpupil = NULL;
lv_obj_t * ui_righteye = NULL;
lv_obj_t * ui_rightpupil = NULL;
lv_obj_t * ui_nose = NULL;

// build funtions

void ui_owl_screen_init(void)
{
    ui_owl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_owl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_owl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_owl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lefteye = lv_obj_create(ui_owl);
    lv_obj_remove_style_all(ui_lefteye);
    lv_obj_set_width(ui_lefteye, 100);
    lv_obj_set_height(ui_lefteye, 100);
    lv_obj_set_x(ui_lefteye, -60);
    lv_obj_set_y(ui_lefteye, -60);
    lv_obj_set_align(ui_lefteye, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lefteye, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_lefteye, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lefteye, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lefteye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftpupil = lv_obj_create(ui_lefteye);
    lv_obj_remove_style_all(ui_leftpupil);
    lv_obj_set_width(ui_leftpupil, 50);
    lv_obj_set_height(ui_leftpupil, 50);
    lv_obj_set_align(ui_leftpupil, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_leftpupil, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftpupil, 65, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftpupil, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftpupil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_righteye = lv_obj_create(ui_owl);
    lv_obj_remove_style_all(ui_righteye);
    lv_obj_set_width(ui_righteye, 100);
    lv_obj_set_height(ui_righteye, 100);
    lv_obj_set_x(ui_righteye, 60);
    lv_obj_set_y(ui_righteye, -60);
    lv_obj_set_align(ui_righteye, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_righteye, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_righteye, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_righteye, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_righteye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightpupil = lv_obj_create(ui_righteye);
    lv_obj_remove_style_all(ui_rightpupil);
    lv_obj_set_width(ui_rightpupil, 50);
    lv_obj_set_height(ui_rightpupil, 50);
    lv_obj_set_align(ui_rightpupil, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_rightpupil, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightpupil, 65, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightpupil, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightpupil, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nose = lv_img_create(ui_owl);
    lv_img_set_src(ui_nose, &ui_img_airowl_1_png);
    lv_obj_set_width(ui_nose, 211);
    lv_obj_set_height(ui_nose, 150);
    lv_obj_set_x(ui_nose, 0);
    lv_obj_set_y(ui_nose, 40);
    lv_obj_set_align(ui_nose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nose, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_nose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_nose, 110);

    lv_obj_add_event_cb(ui_owl, ui_event_owl, LV_EVENT_ALL, NULL);

}

void ui_owl_screen_destroy(void)
{
    if(ui_owl) lv_obj_del(ui_owl);

    // NULL screen variables
    ui_owl = NULL;
    ui_lefteye = NULL;
    ui_leftpupil = NULL;
    ui_righteye = NULL;
    ui_rightpupil = NULL;
    ui_nose = NULL;

}
