// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PM10GRAPH_H
#define UI_PM10GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM10graph
extern void ui_PM10graph_screen_init(void);
extern void ui_PM10graph_screen_destroy(void);
extern lv_obj_t * ui_PM10graph;
extern lv_obj_t * ui_Chart4;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_pmlabel3;
extern lv_obj_t * ui_gpunit3;
extern lv_obj_t * ui_cube3;
extern lv_obj_t * ui_maxlabel3;
extern lv_obj_t * ui_pm10maxvalue;
extern void ui_event_return3(lv_event_t * e);
extern lv_obj_t * ui_return3;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

