// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PM25GRAPH_H
#define UI_PM25GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM25graph
extern void ui_PM25graph_screen_init(void);
extern void ui_PM25graph_screen_destroy(void);
extern lv_obj_t * ui_PM25graph;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_pmlabel2;
extern lv_obj_t * ui_gpunit2;
extern lv_obj_t * ui_cube2;
extern lv_obj_t * ui_maxlabel2;
extern lv_obj_t * ui_pm25maxvalue;
extern void ui_event_return2(lv_event_t * e);
extern lv_obj_t * ui_return2;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

