// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_PM4graph = NULL;
lv_obj_t * ui_Chart2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_pmlabel1 = NULL;
lv_obj_t * ui_gpunit1 = NULL;
lv_obj_t * ui_cube1 = NULL;
lv_obj_t * ui_maxlabel1 = NULL;
lv_obj_t * ui_pm4maxvalue1 = NULL;
lv_obj_t * ui_return1 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_return1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM4graph_screen_init(void)
{
    ui_PM4graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PM4graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM4graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM4graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_PM4graph);
    lv_obj_set_width(ui_Chart2, 201);
    lv_obj_set_height(ui_Chart2, 195);
    lv_obj_set_x(ui_Chart2, 14);
    lv_obj_set_y(ui_Chart2, 4);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart2, 12);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart2, 0, 0);
    lv_chart_set_zoom_x(ui_Chart2, 250);
    lv_chart_set_zoom_y(ui_Chart2, 250);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart2, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart2, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart2, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_PM4graph);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 238);
    lv_obj_set_height(ui_Container2, 59);
    lv_obj_set_x(ui_Container2, 1);
    lv_obj_set_y(ui_Container2, -129);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmlabel1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_pmlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmlabel1, -79);
    lv_obj_set_y(ui_pmlabel1, 2);
    lv_obj_set_align(ui_pmlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pmlabel1, "PM4.0");
    lv_obj_set_style_text_color(ui_pmlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pmlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pmlabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pmlabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_gpunit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit1, -18);
    lv_obj_set_y(ui_gpunit1, 2);
    lv_obj_set_align(ui_gpunit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit1, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_cube1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube1, 5);
    lv_obj_set_y(ui_cube1, -9);
    lv_obj_set_align(ui_cube1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube1, "3");
    lv_obj_set_style_text_color(ui_cube1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxlabel1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_maxlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxlabel1, 39);
    lv_obj_set_y(ui_maxlabel1, 3);
    lv_obj_set_align(ui_maxlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxlabel1, "max");
    lv_obj_set_style_text_color(ui_maxlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxlabel1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4maxvalue1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_pm4maxvalue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4maxvalue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4maxvalue1, 74);
    lv_obj_set_y(ui_pm4maxvalue1, 3);
    lv_obj_set_align(ui_pm4maxvalue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4maxvalue1, "-");
    lv_obj_set_style_text_color(ui_pm4maxvalue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4maxvalue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4maxvalue1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return1 = lv_btn_create(ui_PM4graph);
    lv_obj_set_width(ui_return1, 160);
    lv_obj_set_height(ui_return1, 39);
    lv_obj_set_x(ui_return1, 0);
    lv_obj_set_y(ui_return1, 127);
    lv_obj_set_align(ui_return1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return1, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_return1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "RETURN");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return1, ui_event_return1, LV_EVENT_ALL, NULL);

}

void ui_PM4graph_screen_destroy(void)
{
    if(ui_PM4graph) lv_obj_del(ui_PM4graph);

    // NULL screen variables
    ui_PM4graph = NULL;
    ui_Chart2 = NULL;
    ui_Container2 = NULL;
    ui_pmlabel1 = NULL;
    ui_gpunit1 = NULL;
    ui_cube1 = NULL;
    ui_maxlabel1 = NULL;
    ui_pm4maxvalue1 = NULL;
    ui_return1 = NULL;
    ui_Label3 = NULL;

}
