// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_PM25graph = NULL;
lv_obj_t * ui_Chart3 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_pmlabel2 = NULL;
lv_obj_t * ui_gpunit2 = NULL;
lv_obj_t * ui_cube2 = NULL;
lv_obj_t * ui_maxlabel2 = NULL;
lv_obj_t * ui_pm25maxvalue = NULL;
lv_obj_t * ui_return2 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_return2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM25graph_screen_init(void)
{
    ui_PM25graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PM25graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM25graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_PM25graph);
    lv_obj_set_width(ui_Chart3, 201);
    lv_obj_set_height(ui_Chart3, 195);
    lv_obj_set_x(ui_Chart3, 14);
    lv_obj_set_y(ui_Chart3, 4);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart3, 12);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart3, 0, 0);
    lv_chart_set_zoom_x(ui_Chart3, 250);
    lv_chart_set_zoom_y(ui_Chart3, 250);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_Chart3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart3, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart3, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart3, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_PM25graph);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 238);
    lv_obj_set_height(ui_Container3, 59);
    lv_obj_set_x(ui_Container3, 1);
    lv_obj_set_y(ui_Container3, -129);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmlabel2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_pmlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmlabel2, -79);
    lv_obj_set_y(ui_pmlabel2, 2);
    lv_obj_set_align(ui_pmlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pmlabel2, "PM2.5");
    lv_obj_set_style_text_color(ui_pmlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pmlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pmlabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pmlabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_gpunit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit2, -18);
    lv_obj_set_y(ui_gpunit2, 2);
    lv_obj_set_align(ui_gpunit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit2, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_cube2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube2, 5);
    lv_obj_set_y(ui_cube2, -9);
    lv_obj_set_align(ui_cube2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube2, "3");
    lv_obj_set_style_text_color(ui_cube2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxlabel2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_maxlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxlabel2, 39);
    lv_obj_set_y(ui_maxlabel2, 3);
    lv_obj_set_align(ui_maxlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxlabel2, "max");
    lv_obj_set_style_text_color(ui_maxlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxlabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25maxvalue = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_pm25maxvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25maxvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25maxvalue, 74);
    lv_obj_set_y(ui_pm25maxvalue, 3);
    lv_obj_set_align(ui_pm25maxvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25maxvalue, "-");
    lv_obj_set_style_text_color(ui_pm25maxvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25maxvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25maxvalue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return2 = lv_btn_create(ui_PM25graph);
    lv_obj_set_width(ui_return2, 160);
    lv_obj_set_height(ui_return2, 39);
    lv_obj_set_x(ui_return2, 0);
    lv_obj_set_y(ui_return2, 127);
    lv_obj_set_align(ui_return2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return2, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_return2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "RETURN");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return2, ui_event_return2, LV_EVENT_ALL, NULL);

}

void ui_PM25graph_screen_destroy(void)
{
    if(ui_PM25graph) lv_obj_del(ui_PM25graph);

    // NULL screen variables
    ui_PM25graph = NULL;
    ui_Chart3 = NULL;
    ui_Container3 = NULL;
    ui_pmlabel2 = NULL;
    ui_gpunit2 = NULL;
    ui_cube2 = NULL;
    ui_maxlabel2 = NULL;
    ui_pm25maxvalue = NULL;
    ui_return2 = NULL;
    ui_Label4 = NULL;

}
