// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PM4GRAPH_H
#define UI_PM4GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM4graph
extern void ui_PM4graph_screen_init(void);
extern void ui_PM4graph_screen_destroy(void);
extern lv_obj_t * ui_PM4graph;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_pmlabel1;
extern lv_obj_t * ui_gpunit1;
extern lv_obj_t * ui_cube1;
extern lv_obj_t * ui_maxlabel1;
extern lv_obj_t * ui_pm4maxvalue1;
extern void ui_event_return1(lv_event_t * e);
extern lv_obj_t * ui_return1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

