// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_PM10graph = NULL;
lv_obj_t * ui_Chart4 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_pmlabel3 = NULL;
lv_obj_t * ui_gpunit3 = NULL;
lv_obj_t * ui_cube3 = NULL;
lv_obj_t * ui_maxlabel3 = NULL;
lv_obj_t * ui_pm10maxvalue = NULL;
lv_obj_t * ui_return3 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions
void ui_event_return3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM10graph_screen_init(void)
{
    ui_PM10graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PM10graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM10graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM10graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart4 = lv_chart_create(ui_PM10graph);
    lv_obj_set_width(ui_Chart4, 201);
    lv_obj_set_height(ui_Chart4, 195);
    lv_obj_set_x(ui_Chart4, 14);
    lv_obj_set_y(ui_Chart4, 4);
    lv_obj_set_align(ui_Chart4, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart4, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart4, 12);
    lv_chart_set_range(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart4, 0, 0);
    lv_chart_set_zoom_x(ui_Chart4, 250);
    lv_chart_set_zoom_y(ui_Chart4, 250);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_Chart4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart4, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart4, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart4, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_PM10graph);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 238);
    lv_obj_set_height(ui_Container4, 59);
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, -129);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmlabel3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_pmlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmlabel3, -74);
    lv_obj_set_y(ui_pmlabel3, 2);
    lv_obj_set_align(ui_pmlabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pmlabel3, "PM10.0");
    lv_obj_set_style_text_color(ui_pmlabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pmlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pmlabel3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pmlabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_gpunit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit3, -4);
    lv_obj_set_y(ui_gpunit3, 2);
    lv_obj_set_align(ui_gpunit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit3, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_cube3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube3, 21);
    lv_obj_set_y(ui_cube3, -11);
    lv_obj_set_align(ui_cube3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube3, "3");
    lv_obj_set_style_text_color(ui_cube3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxlabel3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_maxlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxlabel3, 49);
    lv_obj_set_y(ui_maxlabel3, 2);
    lv_obj_set_align(ui_maxlabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxlabel3, "max");
    lv_obj_set_style_text_color(ui_maxlabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxlabel3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10maxvalue = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_pm10maxvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10maxvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10maxvalue, 85);
    lv_obj_set_y(ui_pm10maxvalue, 1);
    lv_obj_set_align(ui_pm10maxvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10maxvalue, "-");
    lv_obj_set_style_text_color(ui_pm10maxvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10maxvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10maxvalue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return3 = lv_btn_create(ui_PM10graph);
    lv_obj_set_width(ui_return3, 160);
    lv_obj_set_height(ui_return3, 39);
    lv_obj_set_x(ui_return3, 0);
    lv_obj_set_y(ui_return3, 127);
    lv_obj_set_align(ui_return3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return3, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_return3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "RETURN");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return3, ui_event_return3, LV_EVENT_ALL, NULL);

}

void ui_PM10graph_screen_destroy(void)
{
    if(ui_PM10graph) lv_obj_del(ui_PM10graph);

    // NULL screen variables
    ui_PM10graph = NULL;
    ui_Chart4 = NULL;
    ui_Container4 = NULL;
    ui_pmlabel3 = NULL;
    ui_gpunit3 = NULL;
    ui_cube3 = NULL;
    ui_maxlabel3 = NULL;
    ui_pm10maxvalue = NULL;
    ui_return3 = NULL;
    ui_Label6 = NULL;

}
