// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PM1GRAPH_H
#define UI_PM1GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM1graph
extern void ui_PM1graph_screen_init(void);
extern void ui_PM1graph_screen_destroy(void);
extern lv_obj_t * ui_PM1graph;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_pmlabel;
extern lv_obj_t * ui_gpunit;
extern lv_obj_t * ui_cube;
extern lv_obj_t * ui_maxlabel;
extern lv_obj_t * ui_pm1maxvalue;
extern void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

