// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_QRCODE_H
#define UI_QRCODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_qrcode
extern void ui_qrcode_screen_init(void);
extern void ui_qrcode_screen_destroy(void);
extern void ui_event_qrcode(lv_event_t * e);
extern lv_obj_t * ui_qrcode;
extern lv_obj_t * ui_qrcodename;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

