// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_TVOCgraph = NULL;
lv_obj_t * ui_Chart5 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_pmlabel4 = NULL;
lv_obj_t * ui_gpunit4 = NULL;
lv_obj_t * ui_maxlabel4 = NULL;
lv_obj_t * ui_tvocmaxvalue = NULL;
lv_obj_t * ui_return4 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_return4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_TVOCgraph_screen_init(void)
{
    ui_TVOCgraph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TVOCgraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVOCgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart5 = lv_chart_create(ui_TVOCgraph);
    lv_obj_set_width(ui_Chart5, 201);
    lv_obj_set_height(ui_Chart5, 195);
    lv_obj_set_x(ui_Chart5, 14);
    lv_obj_set_y(ui_Chart5, 4);
    lv_obj_set_align(ui_Chart5, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart5, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart5, 12);
    lv_chart_set_range(ui_Chart5, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart5, 0, 0);
    lv_chart_set_zoom_x(ui_Chart5, 250);
    lv_chart_set_zoom_y(ui_Chart5, 250);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 5, 2, true, 45);
    lv_chart_set_axis_tick(ui_Chart5, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_Chart5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart5, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart5, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart5, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_TVOCgraph);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 238);
    lv_obj_set_height(ui_Container5, 59);
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -129);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pmlabel4 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_pmlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pmlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pmlabel4, -79);
    lv_obj_set_y(ui_pmlabel4, 2);
    lv_obj_set_align(ui_pmlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pmlabel4, "TVOC");
    lv_obj_set_style_text_color(ui_pmlabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pmlabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pmlabel4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pmlabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit4 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_gpunit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit4, -18);
    lv_obj_set_y(ui_gpunit4, 2);
    lv_obj_set_align(ui_gpunit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit4, "ppb");
    lv_obj_set_style_text_color(ui_gpunit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxlabel4 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_maxlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxlabel4, 36);
    lv_obj_set_y(ui_maxlabel4, 3);
    lv_obj_set_align(ui_maxlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxlabel4, "max");
    lv_obj_set_style_text_color(ui_maxlabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxlabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxlabel4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocmaxvalue = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_tvocmaxvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvocmaxvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvocmaxvalue, 74);
    lv_obj_set_y(ui_tvocmaxvalue, 3);
    lv_obj_set_align(ui_tvocmaxvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvocmaxvalue, "-");
    lv_obj_set_style_text_color(ui_tvocmaxvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvocmaxvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvocmaxvalue, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return4 = lv_btn_create(ui_TVOCgraph);
    lv_obj_set_width(ui_return4, 160);
    lv_obj_set_height(ui_return4, 39);
    lv_obj_set_x(ui_return4, 0);
    lv_obj_set_y(ui_return4, 127);
    lv_obj_set_align(ui_return4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return4, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_return4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RETURN");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return4, ui_event_return4, LV_EVENT_ALL, NULL);

}

void ui_TVOCgraph_screen_destroy(void)
{
    if(ui_TVOCgraph) lv_obj_del(ui_TVOCgraph);

    // NULL screen variables
    ui_TVOCgraph = NULL;
    ui_Chart5 = NULL;
    ui_Container5 = NULL;
    ui_pmlabel4 = NULL;
    ui_gpunit4 = NULL;
    ui_maxlabel4 = NULL;
    ui_tvocmaxvalue = NULL;
    ui_return4 = NULL;
    ui_Label7 = NULL;

}
