// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_TVOCGRAPH_H
#define UI_TVOCGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TVOCgraph
extern void ui_TVOCgraph_screen_init(void);
extern void ui_TVOCgraph_screen_destroy(void);
extern lv_obj_t * ui_TVOCgraph;
extern lv_obj_t * ui_Chart5;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_pmlabel4;
extern lv_obj_t * ui_gpunit4;
extern lv_obj_t * ui_maxlabel4;
extern lv_obj_t * ui_tvocmaxvalue;
extern void ui_event_return4(lv_event_t * e);
extern lv_obj_t * ui_return4;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

