// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef UI_TVOCGRAPH_H
#define UI_TVOCGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TVOCgraph
extern void ui_TVOCgraph_screen_init(void);
extern void ui_TVOCgraph_screen_destroy(void);
extern lv_obj_t * ui_TVOCgraph;
extern lv_obj_t * ui_TVOCchart;
extern lv_obj_t * ui_graphparameter4;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_gpunit4;
extern void ui_event_return4(lv_event_t * e);
extern lv_obj_t * ui_return4;
extern lv_obj_t * ui_returnlabel4;
extern lv_obj_t * ui_graphparameter12;
extern lv_obj_t * ui_graphparameter15;
extern lv_obj_t * ui_tvocavg;
extern lv_obj_t * ui_tvocmax;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

