// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Tempgraph = NULL;
lv_obj_t * ui_tempchart = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_return = NULL;
lv_obj_t * ui_graphparameter = NULL;
lv_obj_t * ui_tempavg= NULL;
lv_obj_t * ui_returnlabel= NULL;
lv_obj_t * ui_graphparameter5 = NULL;
lv_obj_t * ui_graphparameter6= NULL;
lv_obj_t * ui_tempmax = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions
void ui_event_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_Tempgraph_screen_init(void)
{
    ui_Tempgraph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Tempgraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Tempgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tempgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempchart = lv_chart_create(ui_Tempgraph);
    lv_obj_set_width(ui_tempchart, 192);
    lv_obj_set_height(ui_tempchart, 132);
    lv_obj_set_x(ui_tempchart, 20);
    lv_obj_set_y(ui_tempchart, -7);
    lv_obj_set_align(ui_tempchart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_tempchart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_tempchart, 15);
    lv_chart_set_range(ui_tempchart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_tempchart, 0, 0);
    lv_chart_set_axis_tick(ui_tempchart, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_tempchart, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_tempchart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_obj_set_style_bg_color(ui_tempchart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempchart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_graphparameter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter, -84);
    lv_obj_set_y(ui_graphparameter, -143);
    lv_obj_set_align(ui_graphparameter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter, "Temp");
    lv_obj_set_style_text_color(ui_graphparameter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Tempgraph);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 235);
    lv_obj_set_height(ui_Container13, 70);
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, -122);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempavg = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_tempavg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempavg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempavg, -67);
    lv_obj_set_y(ui_tempavg, -106);
    lv_obj_set_align(ui_tempavg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempavg, "-");
    lv_obj_set_style_text_color(ui_tempavg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempavg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempavg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return = lv_btn_create(ui_Tempgraph);
    lv_obj_set_width(ui_return, 224);
    lv_obj_set_height(ui_return, 37);
    lv_obj_set_x(ui_return, -2);
    lv_obj_set_y(ui_return, 85);
    lv_obj_set_align(ui_return, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_returnlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel, 6);
    lv_obj_set_y(ui_returnlabel, 86);
    lv_obj_set_align(ui_returnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter5 = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_graphparameter5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter5, -95);
    lv_obj_set_y(ui_graphparameter5, -106);
    lv_obj_set_align(ui_graphparameter5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter5, "avg");
    lv_obj_set_style_text_color(ui_graphparameter5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter6 = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_graphparameter6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter6, 20);
    lv_obj_set_y(ui_graphparameter6, -106);
    lv_obj_set_align(ui_graphparameter6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter6, "max");
    lv_obj_set_style_text_color(ui_graphparameter6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempmax = lv_label_create(ui_Tempgraph);
    lv_obj_set_width(ui_tempmax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempmax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempmax, 58);
    lv_obj_set_y(ui_tempmax, -107);
    lv_obj_set_align(ui_tempmax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempmax, "-");
    lv_obj_set_style_text_color(ui_tempmax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempmax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempmax, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Tempgraph);
    lv_img_set_src(ui_Image1, &ui_img_582762761);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -34);
    lv_obj_set_y(ui_Image1, -138);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_return, ui_event_return, LV_EVENT_ALL, NULL);

}

void ui_Tempgraph_screen_destroy(void)
{
    if(ui_Tempgraph) lv_obj_del(ui_Tempgraph);

    // NULL screen variables
    ui_Tempgraph = NULL;
    ui_tempchart = NULL;
    ui_graphparameter = NULL;
    ui_Container13 = NULL;
    ui_tempavg = NULL;
    ui_return = NULL;
    ui_returnlabel = NULL;
    ui_graphparameter5 = NULL;
    ui_graphparameter6 = NULL;
    ui_tempmax = NULL;
    ui_Image1 = NULL;

}