// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"
#include "Voice_assistant.h"

lv_obj_t * ui_voiceasistant;
lv_obj_t * ui_speakerbutton;

// event funtions
void ui_event_speakerbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 20000, &ui_dashboard_screen_init);
    }
     if(event_code == LV_EVENT_LONG_PRESSED) {
        initVoiceAssistantTask();  
    }
}

void ui_voiceasistant_screen_init(void)
{
    ui_voiceasistant = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_voiceasistant, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_voiceasistant, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_voiceasistant, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speakerbutton = lv_imgbtn_create(ui_voiceasistant);
    lv_imgbtn_set_src(ui_speakerbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_speaker_png, NULL);
    lv_obj_set_width(ui_speakerbutton, 217);
    lv_obj_set_height(ui_speakerbutton, 216);
    lv_obj_set_align(ui_speakerbutton, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_speakerbutton, ui_event_speakerbutton, LV_EVENT_ALL, NULL);

}

void ui_voiceasistant_screen_destroy(void)
{
    if(ui_voiceasistant) lv_obj_del(ui_voiceasistant);

    ui_voiceasistant = NULL;
    ui_speakerbutton = NULL;

}
