// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_dashboard = NULL;
lv_obj_t * ui_headerContainer = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_wifi = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_pm1Container = NULL;
lv_obj_t * ui_pm1Button = NULL;
lv_obj_t * ui_pm1value = NULL;
lv_obj_t * ui_pm1label = NULL;
lv_obj_t * ui_pm1unit = NULL;
lv_obj_t * ui_pm1cube = NULL;
lv_obj_t * ui_pm25Container = NULL;
lv_obj_t * ui_pm25Button = NULL;
lv_obj_t * ui_pm25label = NULL;
lv_obj_t * ui_pm25value = NULL;
lv_obj_t * ui_pm25unit = NULL;
lv_obj_t * ui_pm25cube = NULL;
lv_obj_t * ui_pm10Container = NULL;
lv_obj_t * ui_pm10Button = NULL;
lv_obj_t * ui_pm10value = NULL;
lv_obj_t * ui_pm10label = NULL;
lv_obj_t * ui_pm10unit = NULL;
lv_obj_t * ui_pm10cube = NULL;

// event funtions
void ui_event_dashboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        
        _ui_screen_change(&ui_owl, LV_SCR_LOAD_ANIM_FADE_ON, 1000, 15000, &ui_owl_screen_init);
    }
}

void ui_event_PM1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM1graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM1graph_screen_init);
    }
}

void ui_event_PM25Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM25graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM25graph_screen_init);
    }
}

void ui_event_PM10Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PM10graph, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_PM10graph_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_qrcode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_qrcode_screen_init);
    }
}

void ui_dashboard_screen_init(void)
{
    ui_dashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dashboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dashboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerContainer = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_headerContainer);
    lv_obj_set_width(ui_headerContainer, 239);
    lv_obj_set_height(ui_headerContainer, 40);
    lv_obj_set_x(ui_headerContainer, -1);
    lv_obj_set_y(ui_headerContainer, -139);
    lv_obj_set_align(ui_headerContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_headerContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_headerContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_headerContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_headerContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_headerContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -2);
    lv_obj_set_y(ui_time, 1);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:25:45");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_Inter20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_headerContainer);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, -87);
    lv_obj_set_y(ui_date, 1);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "XX-XX");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_Inter20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_img_create(ui_headerContainer);
    lv_img_set_src(ui_wifi, &ui_img_wifi_off_png);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi, 90);
    lv_obj_set_y(ui_wifi, 2);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifi, 170);

    ui_Button3 = lv_btn_create(ui_dashboard);
    lv_obj_set_width(ui_Button3, 224);
    lv_obj_set_height(ui_Button3, 27);
    lv_obj_set_x(ui_Button3, -1);
    lv_obj_set_y(ui_Button3, -140);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_Button3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    
    ui_pm1Container = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_pm1Container);
    lv_obj_set_width(ui_pm1Container, 239);
    lv_obj_set_height(ui_pm1Container, 94);
    lv_obj_set_x(ui_pm1Container, -1);
    lv_obj_set_y(ui_pm1Container, -73);
    lv_obj_set_align(ui_pm1Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pm1Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm1Container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm1Container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1Button = lv_btn_create(ui_pm1Container);
    lv_obj_set_width( ui_pm1Button, 221);
    lv_obj_set_height( ui_pm1Button, 70);
    lv_obj_set_x( ui_pm1Button, 1 );
    lv_obj_set_y( ui_pm1Button, -2 );
    lv_obj_set_align( ui_pm1Button, LV_ALIGN_CENTER );
    lv_obj_set_style_radius(ui_pm1Button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pm1Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_pm1Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pm1Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_pm1Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_pm1Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

    ui_pm1label = lv_label_create(ui_pm1Container);
    lv_obj_set_width(ui_pm1label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1label, -65);
    lv_obj_set_y(ui_pm1label, -20);
    lv_obj_set_align(ui_pm1label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1label, "PM1.0");
    lv_obj_set_style_text_color(ui_pm1label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1label, &ui_font_Inter28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1unit = lv_label_create(ui_pm1Container);
    lv_obj_set_width(ui_pm1unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1unit, -77);
    lv_obj_set_y(ui_pm1unit, 25);
    lv_obj_set_align(ui_pm1unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm1unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1unit, &ui_font_Inter22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1cube = lv_label_create(ui_pm1Container);
    lv_obj_set_width(ui_pm1cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1cube, -43);
    lv_obj_set_y(ui_pm1cube, 15);
    lv_obj_set_align(ui_pm1cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1cube, "3");
    lv_obj_set_style_text_color(ui_pm1cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1cube, &ui_font_Inter15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1value = lv_label_create(ui_pm1Container);
    lv_obj_set_width(ui_pm1value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1value, 54);
    lv_obj_set_y(ui_pm1value, 2);
    lv_obj_set_align(ui_pm1value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1value, "0");
    lv_obj_set_style_text_color(ui_pm1value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1value, &ui_font_Inter44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Container = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_pm25Container);
    lv_obj_set_width(ui_pm25Container, 239);
    lv_obj_set_height(ui_pm25Container, 94);
    lv_obj_set_x(ui_pm25Container, -1);
    lv_obj_set_y(ui_pm25Container, 20);
    lv_obj_set_align(ui_pm25Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm25Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pm25Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm25Container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm25Container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25unit = lv_label_create(ui_pm25Container);
    lv_obj_set_width(ui_pm25unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25unit, -77);
    lv_obj_set_y(ui_pm25unit, 25);
    lv_obj_set_align(ui_pm25unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm25unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25unit, &ui_font_Inter22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25cube = lv_label_create(ui_pm25Container);
    lv_obj_set_width(ui_pm25cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25cube, -43);
    lv_obj_set_y(ui_pm25cube, 15);
    lv_obj_set_align(ui_pm25cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25cube, "3");
    lv_obj_set_style_text_color(ui_pm25cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25cube, &ui_font_Inter15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Button = lv_btn_create(ui_pm25Container);
    lv_obj_set_width( ui_pm25Button, 221);
    lv_obj_set_height( ui_pm25Button, 70);
    lv_obj_set_x( ui_pm25Button, 1 );
    lv_obj_set_y( ui_pm25Button, -2 );
    lv_obj_set_align( ui_pm25Button, LV_ALIGN_CENTER );
    lv_obj_set_style_radius(ui_pm25Button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pm25Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_pm25Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pm25Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_pm25Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_pm25Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


    ui_pm25value = lv_label_create(ui_pm25Container);
    lv_obj_set_width(ui_pm25value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25value, 54);
    lv_obj_set_y(ui_pm25value, 2);
    lv_obj_set_align(ui_pm25value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25value, "0");
    lv_obj_set_style_text_color(ui_pm25value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25value, &ui_font_Inter44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25label = lv_label_create(ui_pm25Container);
    lv_obj_set_width(ui_pm25label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25label, -65);
    lv_obj_set_y(ui_pm25label, -20);
    lv_obj_set_align(ui_pm25label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25label, "PM2.5");
    lv_obj_set_style_text_color(ui_pm25label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25label, &ui_font_Inter28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Container = lv_obj_create(ui_dashboard);
    lv_obj_remove_style_all(ui_pm10Container);
    lv_obj_set_width(ui_pm10Container, 239);
    lv_obj_set_height(ui_pm10Container, 94);
    lv_obj_set_x(ui_pm10Container, -1);
    lv_obj_set_y(ui_pm10Container, 113);
    lv_obj_set_align(ui_pm10Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm10Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pm10Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm10Container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm10Container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Button = lv_btn_create(ui_pm10Container);
    lv_obj_set_width( ui_pm10Button, 221);
    lv_obj_set_height( ui_pm10Button, 70);
    lv_obj_set_x( ui_pm10Button, 1 );
    lv_obj_set_y( ui_pm10Button, -2 );
    lv_obj_set_align( ui_pm10Button, LV_ALIGN_CENTER );
    lv_obj_set_style_radius(ui_pm10Button, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pm10Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_bg_opa(ui_pm10Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pm10Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
    lv_obj_set_style_border_opa(ui_pm10Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_pm10Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);


    ui_pm10label = lv_label_create(ui_pm10Container);
    lv_obj_set_width(ui_pm10label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10label, -65);
    lv_obj_set_y(ui_pm10label, -20);
    lv_obj_set_align(ui_pm10label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10label, "PM10.0");
    lv_obj_set_style_text_color(ui_pm10label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10label, &ui_font_Inter28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10unit = lv_label_create(ui_pm10Container);
    lv_obj_set_width(ui_pm10unit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10unit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10unit, -77);
    lv_obj_set_y(ui_pm10unit, 25);
    lv_obj_set_align(ui_pm10unit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10unit, "ug/m");
    lv_obj_set_style_text_color(ui_pm10unit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10unit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10unit, &ui_font_Inter22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10cube = lv_label_create(ui_pm10Container);
    lv_obj_set_width(ui_pm10cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10cube, -43);
    lv_obj_set_y(ui_pm10cube, 15);
    lv_obj_set_align(ui_pm10cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10cube, "3");
    lv_obj_set_style_text_color(ui_pm10cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10cube, &ui_font_Inter15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10value = lv_label_create(ui_pm10Container);
    lv_obj_set_width(ui_pm10value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10value, 54);
    lv_obj_set_y(ui_pm10value, 2);
    lv_obj_set_align(ui_pm10value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10value, "0");
    lv_obj_set_style_text_color(ui_pm10value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10value, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10value, &ui_font_Inter44, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pm1Button, ui_event_PM1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pm25Button, ui_event_PM25Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pm10Button, ui_event_PM10Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dashboard, ui_event_dashboard, LV_EVENT_ALL, NULL);

}

void ui_dashboard_screen_destroy(void)
{
    if(ui_dashboard) lv_obj_del(ui_dashboard);

    // NULL screen variables
    ui_dashboard = NULL;
    ui_headerContainer = NULL;
    ui_time = NULL;
    ui_date = NULL;
    ui_wifi = NULL;
    ui_Button3 = NULL;
    ui_pm1Container = NULL;
    ui_pm1Button = NULL;
    ui_pm1label = NULL;
    ui_pm1unit = NULL;
    ui_pm1cube = NULL;
    ui_pm1value = NULL;
    ui_pm25Button = NULL;
    ui_pm25value = NULL;
    ui_pm25label = NULL;
    ui_pm25Container = NULL;
    ui_pm25unit = NULL;
    ui_pm25cube = NULL;
    ui_pm10Container = NULL;
    ui_pm10Button = NULL;
    ui_pm10label = NULL;
    ui_pm10unit = NULL;
    ui_pm10cube = NULL;
    ui_pm10value = NULL;
}
