// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#include "ui.h"

lv_obj_t * ui_ota;
lv_obj_t * ui_otalabel;
lv_obj_t * ui_otaimage;

// event funtions

// build funtions

void ui_ota_screen_init(void)
{
    ui_ota = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ota, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_otalabel = lv_label_create(ui_ota);
    lv_obj_set_width(ui_otalabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_otalabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_otalabel, -1);
    lv_obj_set_y(ui_otalabel, -93);
    lv_obj_set_align(ui_otalabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_otalabel, "OTA IN PROGRESS");
    lv_obj_set_style_text_font(ui_otalabel, &ui_font_Inter22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_otaimage = lv_img_create(ui_ota);
    lv_img_set_src(ui_otaimage, &ui_img_ota_icon_png);
    lv_obj_set_width(ui_otaimage, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_otaimage, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_otaimage, 0);
    lv_obj_set_y(ui_otaimage, 22);
    lv_obj_set_align(ui_otaimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_otaimage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_otaimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
}

void ui_ota_screen_destroy(void)
{
    if(ui_ota) lv_obj_del(ui_ota);

    // NULL screen variables
    ui_ota = NULL;
    ui_otalabel = NULL;
    ui_otaimage = NULL;

}
