// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef UI_OTA_H
#define UI_OTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ota
extern void ui_ota_screen_init(void);
extern void ui_ota_screen_destroy(void);
extern lv_obj_t * ui_ota;
extern lv_obj_t * ui_otalabel;
extern lv_obj_t * ui_otaimage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

