// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_PM1GRAPH_H
#define UI_PM1GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM1graph
extern void ui_PM1graph_screen_init(void);
extern void ui_PM1graph_screen_destroy(void);
extern lv_obj_t * ui_PM1graph;
extern lv_obj_t * ui_pm1Chart;
extern lv_obj_t * ui_pm1gContainer;
extern lv_obj_t * ui_pm1label3;
extern lv_obj_t * ui_gpunit13;
extern lv_obj_t * ui_cube13;
extern lv_obj_t * ui_maxlabel13;
extern lv_obj_t * ui_pm1maxvalue;
extern void ui_event_return13(lv_event_t * e);
extern lv_obj_t * ui_return13;
extern lv_obj_t * ui_Label61;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

