// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_PM1graph = NULL;
lv_obj_t * ui_pm1Chart = NULL;
lv_obj_t * ui_pm1gContainer = NULL;
lv_obj_t * ui_pm1label3 = NULL;
lv_obj_t * ui_gpunit13 = NULL;
lv_obj_t * ui_cube13 = NULL;
lv_obj_t * ui_maxlabel13 = NULL;
lv_obj_t * ui_pm1maxvalue = NULL;
lv_obj_t * ui_return13 = NULL;
lv_obj_t * ui_Label61 = NULL;

void ui_event_return13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM1graph_screen_init(void)
{
    ui_PM1graph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PM1graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM1graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM1graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1Chart = lv_chart_create(ui_PM1graph);
    lv_obj_set_width(ui_pm1Chart, 192);
    lv_obj_set_height(ui_pm1Chart, 202);
    lv_obj_set_x(ui_pm1Chart, 15);
    lv_obj_set_y(ui_pm1Chart, -5);
    lv_obj_set_align(ui_pm1Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_pm1Chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_pm1Chart, 12);
    lv_chart_set_range(ui_pm1Chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_pm1Chart, 0, 0);
    lv_chart_set_zoom_x(ui_pm1Chart, 250);
    lv_chart_set_zoom_y(ui_pm1Chart, 250);
    lv_chart_set_axis_tick(ui_pm1Chart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_pm1Chart, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_pm1Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_pm1Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm1Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pm1Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm1Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm1Chart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_pm1Chart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1Chart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1Chart, &ui_font_Inter16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_pm1gContainer = lv_obj_create(ui_PM1graph);
    lv_obj_remove_style_all(ui_pm1gContainer);
    lv_obj_set_width(ui_pm1gContainer, 238);
    lv_obj_set_height(ui_pm1gContainer, 43);
    lv_obj_set_x(ui_pm1gContainer, 3);
    lv_obj_set_y(ui_pm1gContainer, -135);
    lv_obj_set_align(ui_pm1gContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm1gContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_pm1gContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pm1gContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pm1gContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1label3 = lv_label_create(ui_pm1gContainer);
    lv_obj_set_width(ui_pm1label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1label3, -82);
    lv_obj_set_y(ui_pm1label3, 2);
    lv_obj_set_align(ui_pm1label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1label3, "PM1");
    lv_obj_set_style_text_color(ui_pm1label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_pm1label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1label3, &ui_font_Inter22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit13 = lv_label_create(ui_pm1gContainer);
    lv_obj_set_width(ui_gpunit13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit13, -24);
    lv_obj_set_y(ui_gpunit13, 2);
    lv_obj_set_align(ui_gpunit13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit13, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit13, &ui_font_Inter16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube13 = lv_label_create(ui_pm1gContainer);
    lv_obj_set_width(ui_cube13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube13, -11);
    lv_obj_set_y(ui_cube13, -12);
    lv_obj_set_align(ui_cube13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube13, "3");
    lv_obj_set_style_text_color(ui_cube13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube13, &ui_font_Inter14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_maxlabel13 = lv_label_create(ui_pm1gContainer);
    lv_obj_set_width(ui_maxlabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxlabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxlabel13, 47);
    lv_obj_set_y(ui_maxlabel13, -1);
    lv_obj_set_align(ui_maxlabel13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxlabel13, "avg : ");
    lv_obj_set_style_text_color(ui_maxlabel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_maxlabel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_maxlabel13, &ui_font_Inter16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1maxvalue = lv_label_create(ui_pm1gContainer);
    lv_obj_set_width(ui_pm1maxvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1maxvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1maxvalue, 91);
    lv_obj_set_y(ui_pm1maxvalue, 1);
    lv_obj_set_align(ui_pm1maxvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1maxvalue, "-");
    lv_obj_set_style_text_color(ui_pm1maxvalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1maxvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1maxvalue, &ui_font_Inter20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return13 = lv_btn_create(ui_PM1graph);
    lv_obj_set_width(ui_return13, 223);
    lv_obj_set_height(ui_return13, 39);
    lv_obj_set_x(ui_return13, -1);
    lv_obj_set_y(ui_return13, 128);
    lv_obj_set_align(ui_return13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_return13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_return13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_return13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return13, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label61 = lv_label_create(ui_return13);
    lv_obj_set_width(ui_Label61, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label61, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label61, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label61, "RETURN");
    lv_obj_set_style_text_color(ui_Label61, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label61, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label61, &ui_font_Inter20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return13, ui_event_return13, LV_EVENT_ALL, NULL);

}

void ui_PM1graph_screen_destroy(void)
{
    if(ui_PM1graph) lv_obj_del(ui_PM1graph);

    // NULL screen variables
    ui_PM1graph = NULL;
    ui_pm1Chart = NULL;
    ui_pm1gContainer = NULL;
    ui_pm1label3 = NULL;
    ui_gpunit13 = NULL;
    ui_cube13 = NULL;
    ui_maxlabel13 = NULL;
    ui_pm1maxvalue = NULL;
    ui_return13 = NULL;
    ui_Label61 = NULL;

}
