// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_tempgraph = NULL;
lv_obj_t * ui_tempChart = NULL;
lv_obj_t * ui_tempgContainer = NULL;
lv_obj_t * ui_tempglabel = NULL;
lv_obj_t * ui_tempgunit4 = NULL;
lv_obj_t * ui_tempgmaxlabel = NULL;
lv_obj_t * ui_tempgmaxvalue = NULL;
lv_obj_t * ui_tempgreturn = NULL;
lv_obj_t * ui_tempgreturn2 = NULL;

void ui_event_return14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_Tempgraph_screen_init(void)
{
    ui_tempgraph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tempgraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tempgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempChart = lv_chart_create(ui_tempgraph);
    lv_obj_set_width(ui_tempChart, 201);
    lv_obj_set_height(ui_tempChart, 195);
    lv_obj_set_x(ui_tempChart, 14);
    lv_obj_set_y(ui_tempChart, 4);
    lv_obj_set_align(ui_tempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_tempChart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_tempChart, 12);
    lv_chart_set_range(ui_tempChart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_tempChart, 0, 0);
    lv_chart_set_zoom_x(ui_tempChart, 250);
    lv_chart_set_zoom_y(ui_tempChart, 250);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_tempChart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_tempChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tempChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempChart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_tempChart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempChart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempChart, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_tempgContainer = lv_obj_create(ui_tempgraph);
    lv_obj_remove_style_all(ui_tempgContainer);
    lv_obj_set_width(ui_tempgContainer, 238);
    lv_obj_set_height(ui_tempgContainer, 59);
    lv_obj_set_x(ui_tempgContainer, 1);
    lv_obj_set_y(ui_tempgContainer, -129);
    lv_obj_set_align(ui_tempgContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempgContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_tempgContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tempgContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tempgContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempglabel = lv_label_create(ui_tempgContainer);
    lv_obj_set_width(ui_tempglabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempglabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempglabel, -79);
    lv_obj_set_y(ui_tempglabel, 2);
    lv_obj_set_align(ui_tempglabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempglabel, "TVOC");
    lv_obj_set_style_text_color(ui_tempglabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempglabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_tempglabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempglabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempgunit4 = lv_img_create(ui_tempgContainer);
    lv_img_set_src(ui_tempgunit4, &ui_img_582762761);
    lv_obj_set_width(ui_tempgunit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempgunit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempgunit4, -4);
    lv_obj_set_y(ui_tempgunit4, 2);
    lv_obj_set_align(ui_tempgunit4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempgunit4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempgunit4, LV_OBJ_FLAG_SCROLLABLE); 

    ui_tempgmaxlabel = lv_label_create(ui_tempgContainer);
    lv_obj_set_width(ui_tempgmaxlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempgmaxlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempgmaxlabel, 39);
    lv_obj_set_y(ui_tempgmaxlabel, 3);
    lv_obj_set_align(ui_tempgmaxlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempgmaxlabel, "max : ");
    lv_obj_set_style_text_color(ui_tempgmaxlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempgmaxlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempgmaxlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempgmaxvalue = lv_label_create(ui_tempgContainer);
    lv_obj_set_width(ui_tempgmaxvalue , LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempgmaxvalue , LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempgmaxvalue , 74);
    lv_obj_set_y(ui_tempgmaxvalue , 3);
    lv_obj_set_align(ui_tempgmaxvalue , LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempgmaxvalue , "-");
    lv_obj_set_style_text_color(ui_tempgmaxvalue , lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempgmaxvalue , 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempgmaxvalue , &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempgreturn = lv_btn_create(ui_tempgraph);
    lv_obj_set_width(ui_tempgreturn, 160);
    lv_obj_set_height(ui_tempgreturn, 39);
    lv_obj_set_x(ui_tempgreturn, 0);
    lv_obj_set_y(ui_tempgreturn, 127);
    lv_obj_set_align(ui_tempgreturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempgreturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tempgreturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tempgreturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tempgreturn, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempgreturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempgreturn2 = lv_label_create(ui_tempgreturn);
    lv_obj_set_width(ui_tempgreturn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempgreturn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempgreturn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempgreturn2, "RETURN");
    lv_obj_set_style_text_color(ui_tempgreturn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempgreturn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempgreturn2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tempgreturn, ui_event_return14, LV_EVENT_ALL, NULL);

}

void ui_Tempgraph_screen_destroy(void)
{
    if(ui_tempgraph) lv_obj_del(ui_tempgraph);

    // NULL screen variables
    ui_tempgraph = NULL;
    ui_tempChart = NULL;
    ui_tempgContainer = NULL;
    ui_tempglabel = NULL;
    ui_tempgunit4 = NULL;
    ui_tempgmaxlabel = NULL;
    ui_tempgmaxvalue = NULL;
    ui_tempgreturn = NULL;
    ui_tempgreturn2 = NULL;

}
