// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef UI_TEMPGRAPH_H
#define UI_TEMPGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tempgraph
extern void ui_Tempgraph_screen_init(void);
extern void ui_Tempgraph_screen_destroy(void);
extern lv_obj_t * ui_tempgraph;
extern lv_obj_t * ui_tempChart;
extern lv_obj_t * ui_tempglabel;
extern lv_obj_t * ui_tempgContainer ;
extern lv_obj_t * ui_tempgunit4;
extern void ui_event_return14(lv_event_t * e);
extern lv_obj_t * ui_tempgreturn;
extern lv_obj_t * ui_tempgreturn2;
extern lv_obj_t *  ui_tempgmaxlabel;
extern lv_obj_t *  ui_tempgmaxvalue;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

