// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef UI_TEMPGRAPH_H
#define UI_TEMPGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Tempgraph
extern void ui_Tempgraph_screen_init(void);
extern void ui_Tempgraph_screen_destroy(void);
extern lv_obj_t * ui_Tempgraph;
extern lv_obj_t * ui_tempchart;
extern lv_obj_t * ui_graphparameter;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_tempavg;
extern void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_returnlabel;
extern lv_obj_t * ui_graphparameter5;
extern lv_obj_t * ui_graphparameter6;
extern lv_obj_t * ui_tempmax;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

