// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_TVOCgraph = NULL;
lv_obj_t * ui_TVOCchart = NULL;
lv_obj_t * ui_TVOCContainer = NULL;
lv_obj_t * ui_TVOClabel = NULL;
lv_obj_t * ui_gunit4 = NULL;
lv_obj_t * ui_tvocmaxlabel = NULL;
lv_obj_t * ui_tvocmaxvalue = NULL;
lv_obj_t * ui_tvocreturn = NULL;
lv_obj_t * ui_Label16 = NULL;

void ui_event_return4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_TVOCgraph_screen_init(void)
{
    ui_TVOCgraph = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TVOCgraph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TVOCgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOCchart = lv_chart_create(ui_TVOCgraph);
    lv_obj_set_width(ui_TVOCchart, 192);
    lv_obj_set_height(ui_TVOCchart, 202);
    lv_obj_set_x(ui_TVOCchart, 15);
    lv_obj_set_y(ui_TVOCchart, -5);
    lv_obj_set_align(ui_TVOCchart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_TVOCchart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_TVOCchart, 12);
    lv_chart_set_range(ui_TVOCchart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_TVOCchart, 0, 0);
    lv_chart_set_zoom_x(ui_TVOCchart, 250);
    lv_chart_set_zoom_y(ui_TVOCchart, 250);
    lv_chart_set_axis_tick(ui_TVOCchart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 6, 1, false, 20);
    lv_chart_set_axis_tick(ui_TVOCchart, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 6, 3, true, 45);
    lv_chart_set_axis_tick(ui_TVOCchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 0);
    lv_obj_set_style_bg_color(ui_TVOCchart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TVOCchart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TVOCchart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVOCchart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TVOCchart, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TVOCchart, lv_color_hex(0xFFFFFF), LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVOCchart, 255, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVOCchart, &lv_font_montserrat_16, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_TVOCContainer = lv_obj_create(ui_TVOCgraph);
    lv_obj_remove_style_all(ui_TVOCContainer);
    lv_obj_set_width(ui_TVOCContainer, 238);
    lv_obj_set_height(ui_TVOCContainer, 43);
    lv_obj_set_x(ui_TVOCContainer, 3);
    lv_obj_set_y(ui_TVOCContainer, -135);
    lv_obj_set_align(ui_TVOCContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TVOCContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_TVOCContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TVOCContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TVOCContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TVOClabel = lv_label_create(ui_TVOCContainer);
    lv_obj_set_width(ui_TVOClabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TVOClabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TVOClabel, -82);
    lv_obj_set_y(ui_TVOClabel, 2);
    lv_obj_set_align(ui_TVOClabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TVOClabel, "TVOC");
    lv_obj_set_style_text_color(ui_TVOClabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TVOClabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TVOClabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TVOClabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gunit4 = lv_label_create(ui_TVOCContainer);
    lv_obj_set_width(ui_gunit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gunit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gunit4, -24);
    lv_obj_set_y(ui_gunit4, 2);
    lv_obj_set_align(ui_gunit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gunit4, "ppb");
    lv_obj_set_style_text_color(ui_gunit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gunit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gunit4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocmaxlabel = lv_label_create(ui_TVOCContainer);
    lv_obj_set_width(ui_tvocmaxlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvocmaxlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvocmaxlabel, 47);
    lv_obj_set_y(ui_tvocmaxlabel, -1);
    lv_obj_set_align(ui_tvocmaxlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvocmaxlabel, "avg : ");
    lv_obj_set_style_text_color(ui_tvocmaxlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvocmaxlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvocmaxlabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocmaxvalue = lv_label_create(ui_TVOCContainer);
    lv_obj_set_width(ui_tvocmaxvalue , LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tvocmaxvalue , LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tvocmaxvalue , 91);
    lv_obj_set_y(ui_tvocmaxvalue , 1);
    lv_obj_set_align(ui_tvocmaxvalue , LV_ALIGN_CENTER);
    lv_label_set_text(ui_tvocmaxvalue , "-");
    lv_obj_set_style_text_color(ui_tvocmaxvalue , lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tvocmaxvalue , 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tvocmaxvalue , &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tvocreturn = lv_btn_create(ui_TVOCgraph);
    lv_obj_set_width(ui_tvocreturn, 223);
    lv_obj_set_height(ui_tvocreturn, 39);
    lv_obj_set_x(ui_tvocreturn, -1);
    lv_obj_set_y(ui_tvocreturn, 128);
    lv_obj_set_align(ui_tvocreturn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tvocreturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tvocreturn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_tvocreturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tvocreturn, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tvocreturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_tvocreturn);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "RETURN");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tvocreturn, ui_event_return4, LV_EVENT_ALL, NULL);

}

void ui_TVOCgraph_screen_destroy(void)
{
    if(ui_TVOCgraph) lv_obj_del(ui_TVOCgraph);

    // NULL screen variables
    ui_TVOCgraph = NULL;
    ui_TVOCchart = NULL;
    ui_TVOCContainer = NULL;
    ui_TVOClabel = NULL;
    ui_gunit4 = NULL;
    ui_tvocmaxlabel = NULL;
    ui_tvocmaxvalue = NULL;
    ui_tvocreturn = NULL;
    ui_Label16 = NULL;

}
