// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_dashboard.h"
#include "screens/ui_Intro.h"
#include "screens/ui_qrcode.h"
#include "screens/ui_owl.h"
#include "screens/ui_dashboard.h"
#include "screens/ui_PM1graph.h"
#include "screens/ui_PM4graph.h"
#include "screens/ui_PM25graph.h"
#include "screens/ui_PM10graph.h"
#include "screens/ui_TVOCgraph.h"

///////////////////// VARIABLES ////////////////////

extern void blink_Animation(lv_obj_t * TargetObject, int delay);
extern void open_Animation(lv_obj_t * TargetObject, int delay);
extern void blinkx_Animation(lv_obj_t * TargetObject, int delay);
extern void openx_Animation(lv_obj_t * TargetObject, int delay);
extern void eyeR_Animation(lv_obj_t * TargetObject, int delay);
extern void eyeL_Animation(lv_obj_t * TargetObject, int delay);
extern void eyeright_Animation(lv_obj_t * TargetObject, int delay);
extern void eyeleft_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_matter_qrcode
void ui_matter_qrcode_screen_init(void);
void ui_event_matter_qrcode(lv_event_t * e);
extern lv_obj_t *ui_matter_qrcode;
extern lv_obj_t *ui_matter_label_top;
extern lv_obj_t *ui_matter_qrcode_obj;
extern lv_obj_t *ui_matter_label_bottom;
extern const char *ui_matter_qrcodedata;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_oizom_logo_png);    // assets/oizom_logo.png
LV_IMG_DECLARE(ui_img_airowl_1_png);    // assets/airowl_1.png
LV_IMG_DECLARE(ui_img_airowl_2_png);    // assets/airowl_2.png
LV_IMG_DECLARE(ui_img_582762761);    // assets/celsius-degrees-symbol-of-temperature.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
