// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef _EXAMPLE_PROJECT_UI_H
#define _EXAMPLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Intro.h"
#include "screens/ui_qrcode.h"
#include "screens/ui_owl.h"
#include "screens/ui_dashboard.h"
#include "screens/ui_PM1graph.h"
#include "screens/ui_PM4graph.h"
#include "screens/ui_PM25graph.h"
#include "screens/ui_PM10graph.h"
#include "screens/ui_TVOCgraph.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * blink_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * open_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * blinkx_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * openx_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * eyeR_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * eyeL_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * eyeright_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * eyeleft_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_loho2_png);    // assets/loho2.png
LV_IMG_DECLARE(ui_img_airowl_1_png);    // assets/airowl_1.png
LV_IMG_DECLARE(ui_img_582762761);    // assets/celsius-degrees-symbol-of-temperature.png

// FONTS
LV_FONT_DECLARE(ui_font_clock24);
LV_FONT_DECLARE(ui_font_clock48);
LV_FONT_DECLARE(ui_font_clock_66);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
