// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dashboard
extern void ui_dashboard_screen_init(void);
extern void ui_dashboard_screen_destroy(void);
extern void ui_event_dashboard(lv_event_t * e);
extern lv_obj_t * ui_dashboard;
extern lv_obj_t * ui_Container6;
extern void ui_event_Container7(lv_event_t * e);
extern lv_obj_t * ui_Container7;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_pm1label;
extern lv_obj_t * ui_Container8;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_PM3;
extern lv_obj_t * ui_PM1u2;
extern lv_obj_t * ui_PM1t2;
extern lv_obj_t * ui_pm25label;
extern lv_obj_t * ui_PM1;
extern lv_obj_t * ui_PM1u;
extern lv_obj_t * ui_PM1t;
extern lv_obj_t * ui_RHpercent;
extern lv_obj_t * ui_TVOC;
extern lv_obj_t * ui_TVOCppb;
extern void ui_event_Container9(lv_event_t * e);
extern lv_obj_t * ui_Container9;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_PM4;
extern lv_obj_t * ui_PM1u3;
extern lv_obj_t * ui_PM1t3;
extern lv_obj_t * ui_pm4label;
extern lv_obj_t * ui_Container10;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_PM2;
extern lv_obj_t * ui_PM1u4;
extern lv_obj_t * ui_PM1t4;
extern lv_obj_t * ui_pm10label;
extern void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_tvoclabel;
extern lv_obj_t * ui_clock2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_templabel;
extern lv_obj_t * ui_RHlabel;
extern lv_obj_t * ui_Container1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

