// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_Intro;
lv_obj_t * ui_devicename;
lv_obj_t * ui_firmwareversion;
lv_obj_t * ui_Image1;

// event funtions
void ui_event_Intro(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_qrcode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 8000, &ui_qrcode_screen_init);
    }
}

// build funtions

void ui_Intro_screen_init(void)
{
    ui_Intro = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Intro, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Intro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Intro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_devicename = lv_label_create(ui_Intro);
    lv_obj_set_width(ui_devicename, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_devicename, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_devicename, 0);
    lv_obj_set_y(ui_devicename, 99);
    lv_obj_set_align(ui_devicename, LV_ALIGN_CENTER);
    lv_label_set_text(ui_devicename, "AIROWL");
    lv_obj_set_style_text_font(ui_devicename, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareversion = lv_label_create(ui_Intro);
    lv_obj_set_width(ui_firmwareversion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firmwareversion, 0);
    lv_obj_set_y(ui_firmwareversion, -102);
    lv_obj_set_align(ui_firmwareversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareversion, "version - 2.0");
    lv_obj_set_style_text_font(ui_firmwareversion, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Intro);
    lv_image_set_src(ui_Image1, &ui_img_loho2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -9);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Intro, ui_event_Intro, LV_EVENT_ALL, NULL);

}

void ui_Intro_screen_destroy(void)
{
    if(ui_Intro) lv_obj_del(ui_Intro);

    // NULL screen variables
    ui_Intro = NULL;
    ui_devicename = NULL;
    ui_firmwareversion = NULL;
    ui_Image1 = NULL;

}
