// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_INTRO_H
#define UI_INTRO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Intro
extern void ui_Intro_screen_init(void);
extern void ui_Intro_screen_destroy(void);
extern void ui_event_Intro(lv_event_t * e);
extern lv_obj_t * ui_Intro;
extern lv_obj_t * ui_devicename;
extern lv_obj_t * ui_firmwareversion;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

