// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_PM1graph;
lv_obj_t * ui_PM1chart;
lv_obj_t * ui_PM1chart_Xaxis;
lv_obj_t * ui_PM1chart_Yaxis1;
lv_obj_t * ui_PM1chart_Yaxis2;
lv_obj_t * ui_graphparameter;
lv_obj_t * ui_Container13;
lv_obj_t * ui_gpunit;
lv_obj_t * ui_pm1avg;
lv_obj_t * ui_return;
lv_obj_t * ui_returnlabel;
lv_obj_t * ui_cube;
lv_obj_t * ui_cube1;
lv_obj_t * ui_graphparameter5;
lv_obj_t * ui_graphparameter6;
lv_obj_t * ui_pm1max;

// event funtions
void ui_event_return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM1graph_screen_init(void)
{
    ui_PM1graph = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PM1graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM1graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM1graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM1chart = lv_chart_create(ui_PM1graph);
    lv_obj_set_width(ui_PM1chart, 262);
    lv_obj_set_height(ui_PM1chart, 132);
    lv_obj_set_x(ui_PM1chart, 13);
    lv_obj_set_y(ui_PM1chart, -9);
    lv_obj_set_align(ui_PM1chart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM1chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_PM1chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_PM1chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_PM1chart, 15);
    lv_chart_set_range(ui_PM1chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_PM1chart, 0, 0);
    lv_obj_set_style_bg_color(ui_PM1chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM1chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM1chart_Xaxis = lv_scale_create(ui_PM1chart);
    lv_scale_set_mode(ui_PM1chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_PM1chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_PM1chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_PM1chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_PM1chart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM1chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_PM1chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM1chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_PM1chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM1chart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_scale_set_total_tick_count(ui_PM1chart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM1chart_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM1chart_Xaxis, false);
    ui_PM1chart_Yaxis1 = lv_scale_create(ui_PM1chart);
    lv_scale_set_mode(ui_PM1chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_PM1chart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_PM1chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_PM1chart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_PM1chart,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_PM1chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM1chart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM1chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_PM1chart_Yaxis1,  500, 1800);
    lv_scale_set_total_tick_count(ui_PM1chart_Yaxis1, (11 > 0 ? 11 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM1chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_PM1chart_Yaxis2 = lv_scale_create(ui_PM1chart);
    lv_scale_set_mode(ui_PM1chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_PM1chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_PM1chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_PM1chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_PM1chart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM1chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM1chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM1chart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM1chart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_PM1chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM1chart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM1chart_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_PM1chart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_PM1chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_graphparameter = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_graphparameter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter, -124);
    lv_obj_set_y(ui_graphparameter, -99);
    lv_obj_set_align(ui_graphparameter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter, "PM1.0");
    lv_obj_set_style_text_color(ui_graphparameter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_PM1graph);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 314);
    lv_obj_set_height(ui_Container13, 30);
    lv_obj_set_x(ui_Container13, 1);
    lv_obj_set_y(ui_Container13, -99);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_gpunit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit, -76);
    lv_obj_set_y(ui_gpunit, -98);
    lv_obj_set_align(ui_gpunit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1avg = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_pm1avg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1avg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1avg, 18);
    lv_obj_set_y(ui_pm1avg, -98);
    lv_obj_set_align(ui_pm1avg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1avg, "-");
    lv_obj_set_style_text_color(ui_pm1avg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1avg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return = lv_button_create(ui_PM1graph);
    lv_obj_set_width(ui_return, 245);
    lv_obj_set_height(ui_return, 37);
    lv_obj_set_x(ui_return, 9);
    lv_obj_set_y(ui_return, 85);
    lv_obj_set_align(ui_return, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_returnlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel, 6);
    lv_obj_set_y(ui_returnlabel, 86);
    lv_obj_set_align(ui_returnlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_cube, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube, -59);
    lv_obj_set_y(ui_cube, -104);
    lv_obj_set_align(ui_cube, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube, "3");
    lv_obj_set_style_text_color(ui_cube, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube1 = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_cube1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube1, -59);
    lv_obj_set_y(ui_cube1, -104);
    lv_obj_set_align(ui_cube1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube1, "3");
    lv_obj_set_style_text_color(ui_cube1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter5 = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_graphparameter5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter5, -17);
    lv_obj_set_y(ui_graphparameter5, -97);
    lv_obj_set_align(ui_graphparameter5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter5, "avg");
    lv_obj_set_style_text_color(ui_graphparameter5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter6 = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_graphparameter6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter6, 77);
    lv_obj_set_y(ui_graphparameter6, -96);
    lv_obj_set_align(ui_graphparameter6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter6, "max");
    lv_obj_set_style_text_color(ui_graphparameter6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1max = lv_label_create(ui_PM1graph);
    lv_obj_set_width(ui_pm1max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1max, 116);
    lv_obj_set_y(ui_pm1max, -98);
    lv_obj_set_align(ui_pm1max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1max, "-");
    lv_obj_set_style_text_color(ui_pm1max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm1max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm1max, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return, ui_event_return, LV_EVENT_ALL, NULL);

}

void ui_PM1graph_screen_destroy(void)
{
    if(ui_PM1graph) lv_obj_del(ui_PM1graph);

    // NULL screen variables
    ui_PM1graph = NULL;
    ui_PM1chart = NULL;
    ui_graphparameter = NULL;
    ui_Container13 = NULL;
    ui_gpunit = NULL;
    ui_pm1avg = NULL;
    ui_return = NULL;
    ui_returnlabel = NULL;
    ui_cube = NULL;
    ui_cube1 = NULL;
    ui_graphparameter5 = NULL;
    ui_graphparameter6 = NULL;
    ui_pm1max = NULL;

}
