// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_PM10GRAPH_H
#define UI_PM10GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM10graph
extern void ui_PM10graph_screen_init(void);
extern void ui_PM10graph_screen_destroy(void);
extern lv_obj_t * ui_PM10graph;
extern lv_obj_t * ui_PM10chart;
extern lv_obj_t * ui_PM10chart_Xaxis;
extern lv_obj_t * ui_PM10chart_Yaxis1;
extern lv_obj_t * ui_PM10chart_Yaxis2;
extern lv_obj_t * ui_graphparameter3;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_gpunit3;
extern void ui_event_return3(lv_event_t * e);
extern lv_obj_t * ui_return3;
extern lv_obj_t * ui_returnlabel3;
extern lv_obj_t * ui_cube5;
extern lv_obj_t * ui_graphparameter11;
extern lv_obj_t * ui_graphparameter14;
extern lv_obj_t * ui_pm10avg;
extern lv_obj_t * ui_pm10max;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

