// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_PM1GRAPH_H
#define UI_PM1GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM1graph
extern void ui_PM1graph_screen_init(void);
extern void ui_PM1graph_screen_destroy(void);
extern lv_obj_t * ui_PM1graph;
extern lv_obj_t * ui_PM1chart;
extern lv_obj_t * ui_PM1chart_Xaxis;
extern lv_obj_t * ui_PM1chart_Yaxis1;
extern lv_obj_t * ui_PM1chart_Yaxis2;
extern lv_obj_t * ui_graphparameter;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_gpunit;
extern lv_obj_t * ui_pm1avg;
extern void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_returnlabel;
extern lv_obj_t * ui_cube;
extern lv_obj_t * ui_cube1;
extern lv_obj_t * ui_graphparameter5;
extern lv_obj_t * ui_graphparameter6;
extern lv_obj_t * ui_pm1max;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

