// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_PM10graph;
lv_obj_t * ui_PM10chart;
lv_obj_t * ui_PM10chart_Xaxis;
lv_obj_t * ui_PM10chart_Yaxis1;
lv_obj_t * ui_PM10chart_Yaxis2;
lv_obj_t * ui_graphparameter3;
lv_obj_t * ui_Container15;
lv_obj_t * ui_gpunit3;
lv_obj_t * ui_return3;
lv_obj_t * ui_returnlabel3;
lv_obj_t * ui_cube5;
lv_obj_t * ui_graphparameter11;
lv_obj_t * ui_graphparameter14;
lv_obj_t * ui_pm10avg;
lv_obj_t * ui_pm10max;

// event funtions
void ui_event_return3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM10graph_screen_init(void)
{
    ui_PM10graph = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PM10graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM10graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM10graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM10chart = lv_chart_create(ui_PM10graph);
    lv_obj_set_width(ui_PM10chart, 262);
    lv_obj_set_height(ui_PM10chart, 132);
    lv_obj_set_x(ui_PM10chart, 13);
    lv_obj_set_y(ui_PM10chart, -9);
    lv_obj_set_align(ui_PM10chart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM10chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_PM10chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_PM10chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_PM10chart, 15);
    lv_chart_set_range(ui_PM10chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_PM10chart, 0, 0);
    lv_obj_set_style_bg_color(ui_PM10chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM10chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM10chart_Xaxis = lv_scale_create(ui_PM10chart);
    lv_scale_set_mode(ui_PM10chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_PM10chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_PM10chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_PM10chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_PM10chart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM10chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_PM10chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM10chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_PM10chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM10chart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_scale_set_total_tick_count(ui_PM10chart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM10chart_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM10chart_Xaxis, false);
    ui_PM10chart_Yaxis1 = lv_scale_create(ui_PM10chart);
    lv_scale_set_mode(ui_PM10chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_PM10chart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_PM10chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_PM10chart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_PM10chart,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_PM10chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM10chart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM10chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_PM10chart_Yaxis1,  500, 1800);
    lv_scale_set_total_tick_count(ui_PM10chart_Yaxis1, (11 > 0 ? 11 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM10chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_PM10chart_Yaxis2 = lv_scale_create(ui_PM10chart);
    lv_scale_set_mode(ui_PM10chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_PM10chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_PM10chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_PM10chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_PM10chart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM10chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM10chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM10chart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM10chart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_PM10chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM10chart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM10chart_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_PM10chart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_PM10chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_graphparameter3 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_graphparameter3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter3, -121);
    lv_obj_set_y(ui_graphparameter3, -99);
    lv_obj_set_align(ui_graphparameter3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter3, "PM10");
    lv_obj_set_style_text_color(ui_graphparameter3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_PM10graph);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 314);
    lv_obj_set_height(ui_Container15, 30);
    lv_obj_set_x(ui_Container15, 1);
    lv_obj_set_y(ui_Container15, -99);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit3 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_gpunit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit3, -77);
    lv_obj_set_y(ui_gpunit3, -97);
    lv_obj_set_align(ui_gpunit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit3, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return3 = lv_button_create(ui_PM10graph);
    lv_obj_set_width(ui_return3, 245);
    lv_obj_set_height(ui_return3, 37);
    lv_obj_set_x(ui_return3, 9);
    lv_obj_set_y(ui_return3, 85);
    lv_obj_set_align(ui_return3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return3, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel3 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_returnlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel3, 6);
    lv_obj_set_y(ui_returnlabel3, 86);
    lv_obj_set_align(ui_returnlabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel3, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube5 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_cube5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube5, -59);
    lv_obj_set_y(ui_cube5, -104);
    lv_obj_set_align(ui_cube5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube5, "3");
    lv_obj_set_style_text_color(ui_cube5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube5, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter11 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_graphparameter11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter11, -17);
    lv_obj_set_y(ui_graphparameter11, -97);
    lv_obj_set_align(ui_graphparameter11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter11, "avg");
    lv_obj_set_style_text_color(ui_graphparameter11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter14 = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_graphparameter14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter14, 77);
    lv_obj_set_y(ui_graphparameter14, -96);
    lv_obj_set_align(ui_graphparameter14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter14, "max");
    lv_obj_set_style_text_color(ui_graphparameter14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter14, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10avg = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_pm10avg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10avg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10avg, 18);
    lv_obj_set_y(ui_pm10avg, -98);
    lv_obj_set_align(ui_pm10avg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10avg, "-");
    lv_obj_set_style_text_color(ui_pm10avg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10avg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10max = lv_label_create(ui_PM10graph);
    lv_obj_set_width(ui_pm10max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10max, 116);
    lv_obj_set_y(ui_pm10max, -98);
    lv_obj_set_align(ui_pm10max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10max, "-");
    lv_obj_set_style_text_color(ui_pm10max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm10max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm10max, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return3, ui_event_return3, LV_EVENT_ALL, NULL);

}

void ui_PM10graph_screen_destroy(void)
{
    if(ui_PM10graph) lv_obj_del(ui_PM10graph);

    // NULL screen variables
    ui_PM10graph = NULL;
    ui_PM10chart = NULL;
    ui_graphparameter3 = NULL;
    ui_Container15 = NULL;
    ui_gpunit3 = NULL;
    ui_return3 = NULL;
    ui_returnlabel3 = NULL;
    ui_cube5 = NULL;
    ui_graphparameter11 = NULL;
    ui_graphparameter14 = NULL;
    ui_pm10avg = NULL;
    ui_pm10max = NULL;

}
