// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_PM4graph;
lv_obj_t * ui_PM4chart;
lv_obj_t * ui_PM4chart_Xaxis;
lv_obj_t * ui_PM4chart_Yaxis1;
lv_obj_t * ui_PM4chart_Yaxis2;
lv_obj_t * ui_graphparameter1;
lv_obj_t * ui_Container12;
lv_obj_t * ui_gpunit1;
lv_obj_t * ui_return1;
lv_obj_t * ui_returnlabel1;
lv_obj_t * ui_cube2;
lv_obj_t * ui_graphparameter8;
lv_obj_t * ui_graphparameter9;
lv_obj_t * ui_pm4avg;
lv_obj_t * ui_pm4max;

// event funtions
void ui_event_return1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM4graph_screen_init(void)
{
    ui_PM4graph = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PM4graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM4graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM4graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM4chart = lv_chart_create(ui_PM4graph);
    lv_obj_set_width(ui_PM4chart, 262);
    lv_obj_set_height(ui_PM4chart, 132);
    lv_obj_set_x(ui_PM4chart, 13);
    lv_obj_set_y(ui_PM4chart, -9);
    lv_obj_set_align(ui_PM4chart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM4chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    lv_obj_remove_flag( ui_PM4chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_PM4chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_PM4chart, 15);
    lv_chart_set_range(ui_PM4chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_PM4chart, 0, 0);
    lv_obj_set_style_bg_color(ui_PM4chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM4chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM4chart_Xaxis = lv_scale_create(ui_PM4chart);
    lv_scale_set_mode(ui_PM4chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_PM4chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_PM4chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_PM4chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_PM4chart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM4chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_PM4chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM4chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_PM4chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM4chart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_scale_set_total_tick_count(ui_PM4chart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM4chart_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM4chart_Xaxis, false);
    ui_PM4chart_Yaxis1 = lv_scale_create(ui_PM4chart);
    lv_scale_set_mode(ui_PM4chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_PM4chart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_PM4chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_PM4chart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_PM4chart,
                                                                     LV_PART_MAIN) - lv_obj_get_style_border_width(ui_PM4chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM4chart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM4chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_PM4chart_Yaxis1,  500, 1800);
    lv_scale_set_total_tick_count(ui_PM4chart_Yaxis1, (11 > 0 ? 11 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM4chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_PM4chart_Yaxis2 = lv_scale_create(ui_PM4chart);
    lv_scale_set_mode(ui_PM4chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_PM4chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_PM4chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_PM4chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_PM4chart,
                                                                     LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM4chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM4chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM4chart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM4chart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_PM4chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM4chart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM4chart_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_PM4chart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_PM4chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_graphparameter1 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_graphparameter1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter1, -121);
    lv_obj_set_y(ui_graphparameter1, -99);
    lv_obj_set_align(ui_graphparameter1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter1, "PM4.0");
    lv_obj_set_style_text_color(ui_graphparameter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container12 = lv_obj_create(ui_PM4graph);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 314);
    lv_obj_set_height(ui_Container12, 30);
    lv_obj_set_x(ui_Container12, 1);
    lv_obj_set_y(ui_Container12, -99);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit1 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_gpunit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit1, -76);
    lv_obj_set_y(ui_gpunit1, -98);
    lv_obj_set_align(ui_gpunit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit1, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return1 = lv_button_create(ui_PM4graph);
    lv_obj_set_width(ui_return1, 245);
    lv_obj_set_height(ui_return1, 37);
    lv_obj_set_x(ui_return1, 9);
    lv_obj_set_y(ui_return1, 85);
    lv_obj_set_align(ui_return1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return1, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel1 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_returnlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel1, 6);
    lv_obj_set_y(ui_returnlabel1, 86);
    lv_obj_set_align(ui_returnlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel1, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube2 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_cube2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube2, -59);
    lv_obj_set_y(ui_cube2, -104);
    lv_obj_set_align(ui_cube2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube2, "3");
    lv_obj_set_style_text_color(ui_cube2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter8 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_graphparameter8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter8, -17);
    lv_obj_set_y(ui_graphparameter8, -97);
    lv_obj_set_align(ui_graphparameter8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter8, "avg");
    lv_obj_set_style_text_color(ui_graphparameter8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter9 = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_graphparameter9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter9, 77);
    lv_obj_set_y(ui_graphparameter9, -96);
    lv_obj_set_align(ui_graphparameter9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter9, "max");
    lv_obj_set_style_text_color(ui_graphparameter9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4avg = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_pm4avg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4avg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4avg, 18);
    lv_obj_set_y(ui_pm4avg, -98);
    lv_obj_set_align(ui_pm4avg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4avg, "-");
    lv_obj_set_style_text_color(ui_pm4avg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4avg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4max = lv_label_create(ui_PM4graph);
    lv_obj_set_width(ui_pm4max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4max, 116);
    lv_obj_set_y(ui_pm4max, -98);
    lv_obj_set_align(ui_pm4max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4max, "-");
    lv_obj_set_style_text_color(ui_pm4max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm4max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm4max, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return1, ui_event_return1, LV_EVENT_ALL, NULL);

}

void ui_PM4graph_screen_destroy(void)
{
    if(ui_PM4graph) lv_obj_del(ui_PM4graph);

    // NULL screen variables
    ui_PM4graph = NULL;
    ui_PM4chart = NULL;
    ui_graphparameter1 = NULL;
    ui_Container12 = NULL;
    ui_gpunit1 = NULL;
    ui_return1 = NULL;
    ui_returnlabel1 = NULL;
    ui_cube2 = NULL;
    ui_graphparameter8 = NULL;
    ui_graphparameter9 = NULL;
    ui_pm4avg = NULL;
    ui_pm4max = NULL;

}
