// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_PM25GRAPH_H
#define UI_PM25GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM25graph
extern void ui_PM25graph_screen_init(void);
extern void ui_PM25graph_screen_destroy(void);
extern lv_obj_t * ui_PM25graph;
extern lv_obj_t * ui_PM25chart;
extern lv_obj_t * ui_PM25chart_Xaxis;
extern lv_obj_t * ui_PM25chart_Yaxis1;
extern lv_obj_t * ui_PM25chart_Yaxis2;
extern lv_obj_t * ui_graphparameter2;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_gpunit2;
extern void ui_event_return2(lv_event_t * e);
extern lv_obj_t * ui_return2;
extern lv_obj_t * ui_returnlabel2;
extern lv_obj_t * ui_cube4;
extern lv_obj_t * ui_graphparameter10;
extern lv_obj_t * ui_graphparameter13;
extern lv_obj_t * ui_pm25avg;
extern lv_obj_t * ui_pm25max;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

