// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_PM4GRAPH_H
#define UI_PM4GRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PM4graph
extern void ui_PM4graph_screen_init(void);
extern void ui_PM4graph_screen_destroy(void);
extern lv_obj_t * ui_PM4graph;
extern lv_obj_t * ui_PM4chart;
extern lv_obj_t * ui_PM4chart_Xaxis;
extern lv_obj_t * ui_PM4chart_Yaxis1;
extern lv_obj_t * ui_PM4chart_Yaxis2;
extern lv_obj_t * ui_graphparameter1;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_gpunit1;
extern void ui_event_return1(lv_event_t * e);
extern lv_obj_t * ui_return1;
extern lv_obj_t * ui_returnlabel1;
extern lv_obj_t * ui_cube2;
extern lv_obj_t * ui_graphparameter8;
extern lv_obj_t * ui_graphparameter9;
extern lv_obj_t * ui_pm4avg;
extern lv_obj_t * ui_pm4max;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

