// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#include "../ui.h"

lv_obj_t * ui_PM25graph;
lv_obj_t * ui_PM25chart;
lv_obj_t * ui_PM25chart_Xaxis;
lv_obj_t * ui_PM25chart_Yaxis1;
lv_obj_t * ui_PM25chart_Yaxis2;
lv_obj_t * ui_graphparameter2;
lv_obj_t * ui_Container14;
lv_obj_t * ui_gpunit2;
lv_obj_t * ui_return2;
lv_obj_t * ui_returnlabel2;
lv_obj_t * ui_cube4;
lv_obj_t * ui_graphparameter10;
lv_obj_t * ui_graphparameter13;
lv_obj_t * ui_pm25avg;
lv_obj_t * ui_pm25max;

// event funtions
void ui_event_return2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_dashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_dashboard_screen_init);
    }
}

// build funtions

void ui_PM25graph_screen_init(void)
{
    ui_PM25graph = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PM25graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PM25graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25graph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25chart = lv_chart_create(ui_PM25graph);
    lv_obj_set_width(ui_PM25chart, 262);
    lv_obj_set_height(ui_PM25chart, 132);
    lv_obj_set_x(ui_PM25chart, 13);
    lv_obj_set_y(ui_PM25chart, -9);
    lv_obj_set_align(ui_PM25chart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PM25chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_PM25chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_PM25chart, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_PM25chart, 15);
    lv_chart_set_range(ui_PM25chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_PM25chart, 0, 0);
    lv_obj_set_style_bg_color(ui_PM25chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PM25chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PM25chart_Xaxis = lv_scale_create(ui_PM25chart);
    lv_scale_set_mode(ui_PM25chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_PM25chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_PM25chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_PM25chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_PM25chart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM25chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_PM25chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM25chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_PM25chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM25chart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_scale_set_total_tick_count(ui_PM25chart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM25chart_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM25chart_Xaxis, false);
    ui_PM25chart_Yaxis1 = lv_scale_create(ui_PM25chart);
    lv_scale_set_mode(ui_PM25chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_PM25chart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_PM25chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_PM25chart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_PM25chart,
                                                                      LV_PART_MAIN) - lv_obj_get_style_border_width(ui_PM25chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM25chart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM25chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_PM25chart_Yaxis1,  500, 1800);
    lv_scale_set_total_tick_count(ui_PM25chart_Yaxis1, (11 > 0 ? 11 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM25chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_PM25chart_Yaxis2 = lv_scale_create(ui_PM25chart);
    lv_scale_set_mode(ui_PM25chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_PM25chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_PM25chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_PM25chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_PM25chart,
                                                                      LV_PART_MAIN) + lv_obj_get_style_border_width(ui_PM25chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_PM25chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_PM25chart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_PM25chart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_PM25chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_PM25chart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_PM25chart_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_PM25chart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_PM25chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_graphparameter2 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_graphparameter2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter2, -121);
    lv_obj_set_y(ui_graphparameter2, -99);
    lv_obj_set_align(ui_graphparameter2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter2, "PM2.5");
    lv_obj_set_style_text_color(ui_graphparameter2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_PM25graph);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 314);
    lv_obj_set_height(ui_Container14, 30);
    lv_obj_set_x(ui_Container14, 1);
    lv_obj_set_y(ui_Container14, -99);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit2 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_gpunit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit2, -76);
    lv_obj_set_y(ui_gpunit2, -98);
    lv_obj_set_align(ui_gpunit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit2, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return2 = lv_button_create(ui_PM25graph);
    lv_obj_set_width(ui_return2, 245);
    lv_obj_set_height(ui_return2, 37);
    lv_obj_set_x(ui_return2, 9);
    lv_obj_set_y(ui_return2, 85);
    lv_obj_set_align(ui_return2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return2, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel2 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_returnlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel2, 6);
    lv_obj_set_y(ui_returnlabel2, 86);
    lv_obj_set_align(ui_returnlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel2, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cube4 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_cube4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cube4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cube4, -59);
    lv_obj_set_y(ui_cube4, -104);
    lv_obj_set_align(ui_cube4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cube4, "3");
    lv_obj_set_style_text_color(ui_cube4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cube4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cube4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter10 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_graphparameter10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter10, -17);
    lv_obj_set_y(ui_graphparameter10, -97);
    lv_obj_set_align(ui_graphparameter10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter10, "avg");
    lv_obj_set_style_text_color(ui_graphparameter10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphparameter13 = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_graphparameter13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter13, 77);
    lv_obj_set_y(ui_graphparameter13, -96);
    lv_obj_set_align(ui_graphparameter13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter13, "max");
    lv_obj_set_style_text_color(ui_graphparameter13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter13, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25avg = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_pm25avg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25avg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25avg, 18);
    lv_obj_set_y(ui_pm25avg, -98);
    lv_obj_set_align(ui_pm25avg, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25avg, "-");
    lv_obj_set_style_text_color(ui_pm25avg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25avg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25avg, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25max = lv_label_create(ui_PM25graph);
    lv_obj_set_width(ui_pm25max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25max, 116);
    lv_obj_set_y(ui_pm25max, -98);
    lv_obj_set_align(ui_pm25max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25max, "-");
    lv_obj_set_style_text_color(ui_pm25max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pm25max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pm25max, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return2, ui_event_return2, LV_EVENT_ALL, NULL);

}

void ui_PM25graph_screen_destroy(void)
{
    if(ui_PM25graph) lv_obj_del(ui_PM25graph);

    // NULL screen variables
    ui_PM25graph = NULL;
    ui_PM25chart = NULL;
    ui_graphparameter2 = NULL;
    ui_Container14 = NULL;
    ui_gpunit2 = NULL;
    ui_return2 = NULL;
    ui_returnlabel2 = NULL;
    ui_cube4 = NULL;
    ui_graphparameter10 = NULL;
    ui_graphparameter13 = NULL;
    ui_pm25avg = NULL;
    ui_pm25max = NULL;

}
