// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: example_project

#ifndef UI_QRCODE_H
#define UI_QRCODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_qrcode
extern void ui_qrcode_screen_init(void);
extern void ui_qrcode_screen_destroy(void);
extern void ui_event_qrcode(lv_event_t * e);
extern lv_obj_t * ui_qrcode;
extern lv_obj_t * ui_qrcodename;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

