; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:development]
platform = espressif32 @ 6.10.0
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 460800
monitor_rts = 0
monitor_dtr = 0

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

board_build.filesystem = spiffs
upload_protocol = esptool

board_build.partitions = partitions.csv

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DCONFIG_SPIRAM_SUPPORT
    -DCONFIG_SPIRAM_BOOT_INIT
    -DCONFIG_SPIRAM_USE_MALLOC
    ; -DCONFIG_HEAP_ALLOC_IRAM=1
    ; -DCONFIG_ARDUINO_LOOP_STACK_SIZE=12288
    -DCONFIG_ENABLE_LVGL
    ; -DCONFIG_ENABLE_SENSOR_SEN54
    ; -DCONFIG_ENABLE_SENSOR_SHT
    ; -DCONFIG_ENABLE_OTA_ANEDYA
    ; -DCONFIG_ENABLE_ESP_NOW
    ; -DCONFIG_ESP_MATTER_ENABLE
    ; -DCONFIG_ESP_MATTER_ENABLE_DATA_MODEL  
    -DCONFIG_ENABLE_VOICE_ASSISTANT
    ; -DARDUINO_RUNNING_CORE=1
    ; -DARDUINO_EVENT_RUNNING_CORE=1
    -D CORE_DEBUG_LEVEL=5
    ; -DCONFIG_ARDUINO_LOOP_STACK_SIZE=12288
    ; -DMBEDTLS_SSL_IN_CONTENT_LEN=4096
    ; -DMBEDTLS_SSL_OUT_CONTENT_LEN=2048
    ; -DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC
    ; -DCONFIG_MBEDTLS_DYNAMIC_BUFFER
    -std=gnu++17
    -Iinclude
    -Isrc

build_unflags =
  -std=gnu++11

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git   
    lvgl/lvgl@^8.3.0
    https://github.com/adafruit/Adafruit_CST8XX_Library 
    adafruit/Adafruit BusIO@^1.14.1 
    bblanchon/ArduinoJson@^7.1.0
    links2004/WebSockets@^2.4.1
    ESP32Async/ESPAsyncWebServer@^3.7.6
    https://github.com/pschatzmann/arduino-audio-tools.git#v1.0.1
    https://github.com/pschatzmann/arduino-libopus.git#a1.1.0

lib_extra_dirs = lib
monitor_filters = 
  esp32_exception_decoder
  colorize
  time

; lib_ldf_mode = deep
